# Builds a source-build tarball

parameters:
  # Custom condition to apply to the job
  condition: true

  # Dependent jobs that must be completed before this job will run
  dependsOn:

  # Resource id of the installer build to retrieve source/product tarball's from
  installerBuildResourceId: current

  # The following parameters aren't expected to be passed in rather they are used for encapsulation
  # -----------------------------------------------------------------------------------------------
  centOS7Container: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-source-build-20210714125450-5d87b80
  centOS8Container: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-8-source-build-20211118190102-9355e7b
  centOSStream9Container: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-stream9-20220107135047-4cd394c
  debian9Container: mcr.microsoft.com/dotnet-buildtools/prereqs:debian-stretch-20211001171226-047508b
  debian9Arm64Container: mcr.microsoft.com/dotnet-buildtools/prereqs:debian-9-arm64v8-20220405201138-a251961
  fedora33Container: mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-33-20210222183538-031e7d2
  ubuntu1804Container: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-20210924170306-047508b
  poolInternalAmd64:
    name: NetCore1ESPool-Svc-Internal
    demands: ImageOverride -equals Build.Ubuntu.1804.Amd64
  poolInternalArm64:
    name: Docker-Linux-Arm-Internal
  poolPublicAmd64:
    name: NetCore-Svc-Public
    demands: ImageOverride -equals Build.Ubuntu.1804.Amd64.Open

jobs:
- template: /src/SourceBuild/Arcade/eng/common/templates/job/source-build-build-tarball.yml
  parameters:
    architecture: x64
    condition: ${{ parameters.condition }}
    dependsOn: ${{ parameters.dependsOn }}
    ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
      excludeSdkContentTests: true
    installerBuildResourceId: ${{ parameters.installerBuildResourceId }}
    matrix:
      CentOS7-Online:
        _BootstrapPrep: false
        _Container: ${{ parameters.centOS7Container }}
        _EnablePoison: false
        _ExcludeOmniSharpTests: true
        _RunOnline: true
      CentOS7-Offline:
        _BootstrapPrep: false
        _Container: ${{ parameters.centOS7Container }}
        _EnablePoison: false
        _ExcludeOmniSharpTests: true
        _RunOnline: false
      ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
        CentOS8-Offline:
          _BootstrapPrep: false
          _Container: ${{ parameters.centOS8Container }}
          _EnablePoison: false
          _ExcludeOmniSharpTests: false
          _RunOnline: false
        CentOSStream9-Offline:
          _BootstrapPrep: false
          _Container: ${{ parameters.centOSStream9Container }}
          _EnablePoison: false
          _ExcludeOmniSharpTests: false
          _RunOnline: false
        Fedora33-Offline:
          _BootstrapPrep: false
          _Container: ${{ parameters.fedora33Container }}
          _EnablePoison: true
          _ExcludeOmniSharpTests: false
          _RunOnline: false
        Ubuntu1804-Offline:
          _BootstrapPrep: false
          _Container: ${{ parameters.ubuntu1804Container }}
          _EnablePoison: false
          _ExcludeOmniSharpTests: false
          _RunOnline: false
    name: Build_Tarball_x64
    pool:
      ${{ if eq(variables['System.TeamProject'], 'public') }}:
        ${{ parameters.poolPublicAmd64 }}
      ${{ if eq(variables['System.TeamProject'], 'internal') }}:
        ${{ parameters.poolInternalAmd64 }}

- ${{ if eq(variables['System.TeamProject'], 'internal') }}:
  - template: /src/SourceBuild/Arcade/eng/common/templates/job/source-build-build-tarball.yml
    parameters:
      architecture: arm64
      condition: ${{ parameters.condition }}
      dependsOn: ${{ parameters.dependsOn }}
      ${{ if in(variables['Build.Reason'], 'PullRequest') }}:
        excludeSdkContentTests: true
      installerBuildResourceId: ${{ parameters.installerBuildResourceId }}
      matrix:
        ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
          Debian9-Offline:
            _BootstrapPrep: true
            _Container: ${{ parameters.debian9Arm64Container }}
            _EnablePoison: false
            _ExcludeOmniSharpTests: false
            _RunOnline: false
      name: Build_Tarball_arm64
      pool: ${{ parameters.poolInternalArm64 }}

- ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
  - template: /src/SourceBuild/Arcade/eng/common/templates/job/source-build-build-tarball.yml
    parameters:
      architecture: x64
      # Always attempt to run the bootstrap leg (e.g. even when stage 1 tests fail) in order to get a complete accessment of the build status.
      # The bootstrap build will shortcut if the stage 1 build failed.
      condition: and(${{ parameters.condition }}, succeededOrFailed())
      dependsOn: Build_Tarball_x64
      excludeSdkContentTests: true
      installerBuildResourceId: ${{ parameters.installerBuildResourceId }}
      matrix:
        Fedora33-Offline:
          _PreviousSourceBuildArtifact: Build_Tarball_x64 Fedora33-Offline_Artifacts
          _Container: ${{ parameters.fedora33Container }}
          _EnablePoison: false
          _ExcludeOmniSharpTests: false
          _RunOnline: false
      name: Build_Tarball_x64_Using_Previous
      pool:
        ${{ if eq(variables['System.TeamProject'], 'public') }}:
          ${{ parameters.poolPublicAmd64 }}
        ${{ if eq(variables['System.TeamProject'], 'internal') }}:
          ${{ parameters.poolInternalAmd64 }}
      usePreviousArtifacts: true
