//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.TemplateSearch.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizableStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizableStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.TemplateSearch.Common.LocalizableStrings", typeof(LocalizableStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update search cache..
        /// </summary>
        internal static string BlobStoreSourceFileProvider_Exception_FailedToUpdateCache {
            get {
                return ResourceManager.GetString("BlobStoreSourceFileProvider_Exception_FailedToUpdateCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local search cache &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string BlobStoreSourceFileProvider_Exception_LocalCacheDoesNotExist {
            get {
                return ResourceManager.GetString("BlobStoreSourceFileProvider_Exception_LocalCacheDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update search cache. Local search cache will be used instead..
        /// </summary>
        internal static string BlobStoreSourceFileProvider_Warning_LocalCacheWillBeUsed {
            get {
                return ResourceManager.GetString("BlobStoreSourceFileProvider_Warning_LocalCacheWillBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template search cache data is not supported..
        /// </summary>
        internal static string TemplateSearchCache_Exception_NotSupported {
            get {
                return ResourceManager.GetString("TemplateSearchCache_Exception_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template search cache data is not valid..
        /// </summary>
        internal static string TemplateSearchCache_Exception_NotValid {
            get {
                return ResourceManager.GetString("TemplateSearchCache_Exception_NotValid", resourceCulture);
            }
        }
    }
}
