# Static completion script for mycommand
# Generated by System.CommandLine.StaticCompletions

export extern "mycommand" [
    --verbosity(-v): string@["detailed", "diagnostic", "minimal", "normal", "quiet"]
]

