# Static completion definitions for mycommand.
# Generated by `dotnet completions script nushell`.

# Place this file in one of the paths listed in $env.NU_LIB_DIRS
# then `use` it in your config.nu or elsewhere.

# For example, if ~/.config/nushell/lib is in your $env.NU_LIB_DIRS,
# you could place this file as `dotnet-completions.nu` in the above
# directory and then put the following line in your config.nu:
# `use dotnet-completions.nu *`

# Of course, the above assumes that your $env.NU_LIB_DIRS is
# actually populated; refer to
# <https://www.nushell.sh/book/configuration.html> if it isn't.

# Alternatively, you can put this file wherever you want and `use`
# the absolute path to the file:
# `use /path/to/this/file.nu *`

export extern "mycommand" [
    --name: string
]

