# Static completion definitions for my-app.
# Generated by `dotnet completions script nushell`.

# Place this file in one of the paths listed in $env.NU_LIB_DIRS
# then `use` it in your config.nu or elsewhere.

# For example, if ~/.config/nushell/lib is in your $env.NU_LIB_DIRS,
# you could place this file as `dotnet-completions.nu` in the above
# directory and then put the following line in your config.nu:
# `use dotnet-completions.nu *`

# Of course, the above assumes that your $env.NU_LIB_DIRS is
# actually populated; refer to
# <https://www.nushell.sh/book/configuration.html> if it isn't.

# Alternatively, you can put this file wherever you want and `use`
# the absolute path to the file:
# `use /path/to/this/file.nu *`

export extern "my-app" [
    --c
    --v
    --help(-h) # Show help and usage information
]

# Subcommand with a second line
export extern "my-app test" [
    --debug(-d)
    --c
    --help(-h) # Show help and usage information
]

# Print this message or the help of the given subcommand(s)
export extern "my-app help" [
    --c
    --help(-h) # Show help and usage information
]

export extern "my-app help test" [
    --c
    --help(-h) # Show help and usage information
]

