# Static completion script for mycommand
# Generated by System.CommandLine.StaticCompletions

export extern "mycommand" [
    --verbose(-v)
]

export extern "mycommand subcommand" [
    --name: string
    --verbose(-v)
]

