# Static completion script for mycommand
# Generated by System.CommandLine.StaticCompletions

# Dynamic completion function
def "nu-complete mycommand-dynamic" [context: string] {
    ^mycommand complete --position ($context | str length) $context | lines
}

export extern "mycommand" [
    file: string@"nu-complete mycommand-dynamic"
    --project: string@"nu-complete mycommand-dynamic"
]

