# Static completion script for mycommand
# Generated by System.CommandLine.StaticCompletions

export extern "mycommand" [
]

export extern "mycommand subcommand" [
]

export extern "mycommand subcommand nested" [
]

