# Static completion script for my-app
# Generated by System.CommandLine.StaticCompletions

export extern "my-app" [
    --c
    --v
    --help(-h) # Show help and usage information
]

export extern "my-app test" [
    --debug(-d)
    --c
    --help(-h) # Show help and usage information
]

export extern "my-app help" [
    --c
    --help(-h) # Show help and usage information
]

export extern "my-app help test" [
    --c
    --help(-h) # Show help and usage information
]

