<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(CurrentTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../src/Installer/Microsoft.Dotnet.Installation/Internal/ScopedLockFile.cs" Link="ScopedLockFile.cs" />
  </ItemGroup>
</Project>