trigger:
  batch: true
  branches:
    include:
    - master
    - release/*
    - internal/release/3.*

variables:
  - name: teamName
    value: Roslyn-Project-System
  - name: PB_PublishBlobFeedUrl
    value: ''
  - name: _DotNetPublishToBlobFeed
    value: false
  - name: _DotNetArtifactsCategory
    value: .NETCore
  - name: _DotNetValidationArtifactsCategory
    value: .NETCore
  - name: _PublishToAzure
    value: false
  - ${{ if ne(variables['System.TeamProject'], 'public') }}:
    - name: PB_PublishBlobFeedUrl
      value: https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
    - name: _DotNetPublishToBlobFeed
      value: true
    - name: _PublishToAzure
      value: true
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - group: DotNet-CLI-SDLValidation-Params

stages:
- stage: build
  displayName: Build
  jobs:
  - template: /eng/build.yml
    parameters:
      agentOs: Windows_NT
      pool:
        ${{ if eq(variables['System.TeamProject'], 'public') }}:
          name: NetCorePublic-Pool
          queue: BuildPool.Windows.10.Amd64.VS2019.Pre.Open
        ${{ if ne(variables['System.TeamProject'], 'public') }}:
          name: NetCoreInternal-Pool
          queue: buildpool.windows.10.amd64.vs2017
      helixTargetQueue: Windows.10.Amd64.ClientRS5.VS2019.BT.Open
      strategy:
        matrix:
          ${{ if eq(variables['System.TeamProject'], 'public') }}:
            Build_Debug:
              _BuildConfig: Debug
              _PublishType: none
              _SignType: test
              _Test: -test
          Build_Release:
            _BuildConfig: Release
            ${{ if eq(variables['System.TeamProject'], 'public') }}:
              _PublishType: none
              _SignType: test
              _Test: -test
            ${{ if ne(variables['System.TeamProject'], 'public') }}:
              _PublishType: blob
              _SignType: real
              _Test: ''
  - ${{ if eq(variables['System.TeamProject'], 'public') }}:
    - template: /eng/build.yml
      parameters:
        agentOs: Windows_NT_FullFramework
        pool:
          name: NetCorePublic-Pool
          queue: BuildPool.Windows.10.Amd64.VS2019.Pre.Open
        helixTargetQueue: Windows.10.Amd64.ClientRS5.VS2019.BT.Open
        strategy:
          matrix:
            Build_Debug:
              _BuildConfig: Debug
              _PublishType: none
              _SignType: test
            Build_Release:
              _BuildConfig: Release
              _PublishType: none
              _SignType: test

    - template: /eng/build.yml
      parameters:
        agentOs: Windows_NT_TestAsTools
        pool:
          name: NetCorePublic-Pool
          queue: BuildPool.Windows.10.Amd64.VS2019.Pre.Open
        strategy:
          matrix:
            Build_Debug:
              _BuildConfig: Debug
              _PublishType: none
              _SignType: test

    - template: /eng/build.yml
      parameters:
        agentOs: Ubuntu_16_04
        pool:
          name: NetCorePublic-Pool
          queue: BuildPool.Ubuntu.1604.Amd64.Open
        helixTargetQueue: Ubuntu.1604.Amd64.Open
        strategy:
          matrix:
            Build_Debug:
              _BuildConfig: Debug
              _PublishType: none
              _SignType: test
            Build_Release:
              _BuildConfig: Release
              _PublishType: none
              _SignType: test

    - template: /eng/build.yml
      parameters:
        agentOs: Darwin
        pool:
          name: Hosted macOS
        helixTargetQueue: OSX.1014.Amd64.Open
        strategy:
          matrix:
            Build_Debug:
              _BuildConfig: Debug
              _PublishType: none
              _SignType: test
            Build_Release:
              _BuildConfig: Release
              _PublishType: none
              _SignType: test

    - template: /eng/build.yml
      parameters:
        agentOs: Windows_Perf_CI
        pool:
          name: NetCorePublic-Pool
          queue: BuildPool.Windows.10.Amd64.VS2019.Pre.Open
        strategy:
          matrix:
            Build_Release:
              _BuildConfig: Release
              _PublishType: none
              _SignType: test

    - template: /eng/build.yml
      parameters:
        agentOs: Windows_Perf_CI_FullFramework
        pool:
          name: NetCorePublic-Pool
          queue: buildpool.windows.10.amd64.vs2017.open
        strategy:
          matrix:
            Build_Release:
              _BuildConfig: Release
              _PublishType: none
              _SignType: test

    - template: /eng/build.yml
      parameters:
        agentOs: Linux_Perf_CI
        pool:
          name: NetCorePublic-Pool
          queue: BuildPool.Ubuntu.1604.Amd64.Open
        strategy:
          matrix:
            Build_Release:
              _BuildConfig: Release
              _PublishType: none
              _SignType: test

  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - template: /eng/common/templates/job/publish-build-assets.yml
      parameters:
        publishUsingPipelines: true
        dependsOn:
          - Windows_NT
        queue:
          name: Hosted VS2017
- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
  - template: /eng/common/templates/post-build/post-build.yml
    parameters:
      enableSymbolValidation: false
      SDLValidationParameters:
        enable: true
        params: ' -SourceToolsList @("policheck","credscan")
        -TsaInstanceURL $(_TsaInstanceURL)
        -TsaProjectName $(_TsaProjectName)
        -TsaNotificationEmail $(_TsaNotificationEmail)
        -TsaCodebaseAdmin $(_TsaCodebaseAdmin)
        -TsaBugAreaPath $(_TsaBugAreaPath)
        -TsaIterationPath $(_TsaIterationPath)
        -TsaRepositoryName "dotnet-sdk"
        -TsaCodebaseName "dotnet-sdk"
        -TsaPublish $True'

- stage: helix_tests
  displayName: controlled environment performance tests
  dependsOn: build
  condition: and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - template: /eng/build.yml
    parameters:
      agentOs: Windows_Perf_Helix
      pool:
        name: Hosted VS2017
      strategy:
        matrix:
          Build_Release:
            _BuildConfig: Release
            _PublishType: none
            _SignType: test
            _DotNetPublishToBlobFeed: false

  - template: /eng/build.yml
    parameters:
      agentOs: Windows_Perf_Helix_Fullframework
      pool:
        name: Hosted VS2017
      strategy:
        matrix:
          Build_Release:
            _BuildConfig: Release
            _PublishType: none
            _SignType: test
            _DotNetPublishToBlobFeed: false

  - template: /eng/build.yml
    parameters:
      agentOs: Linux_Perf_Helix
      pool:
        name: Hosted Ubuntu 1604
      strategy:
        matrix:
          Build_Release:
            _BuildConfig: Release
            _PublishType: none
            _SignType: test
            _DotNetPublishToBlobFeed: false
