trigger:
  batch: true
  branches:
    include:
    - master
    - release/*
    - internal/release/3.*
    - internal/release/5.*

variables:
  - name: teamName
    value: Roslyn-Project-System
  - name: PB_PublishBlobFeedUrl
    value: ''
  - name: _DotNetPublishToBlobFeed
    value: false
  - name: _DotNetArtifactsCategory
    value: .NETCore
  - name: _DotNetValidationArtifactsCategory
    value: .NETCore
  - name: _PublishToAzure
    value: false
  - ${{ if ne(variables['System.TeamProject'], 'public') }}:
    - name: PB_PublishBlobFeedUrl
      value: https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
    - name: _DotNetPublishToBlobFeed
      value: true
    - name: _PublishToAzure
      value: true
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - group: DotNet-CLI-SDLValidation-Params

stages:
- stage: build
  displayName: Build
  jobs:
  - template: /eng/build.yml
    parameters:
      agentOs: Windows_NT
      pool:
        ${{ if eq(variables['System.TeamProject'], 'public') }}:
          name: NetCore-Svc-Public
          demands: ImageOverride -equals windows.vs2019.amd64.open
        ${{ if ne(variables['System.TeamProject'], 'public') }}:
          name: NetCore1ESPool-Svc-Internal
          demands: ImageOverride -equals windows.vs2019.amd64
      helixTargetQueue: Windows.Amd64.VS2022.Pre.Open
      strategy:
        matrix:
          ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
            Build_Debug:
              _BuildConfig: Debug
              _PublishType: none
              _SignType: test
              _Test: -test
          Build_Release:
            _BuildConfig: Release
            ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
              _PublishType: none
              _SignType: test
              _Test: -test
            ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
              _PublishType: blob
              _SignType: real
              _Test: ''
  - ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
    - template: /eng/build.yml
      parameters:
        agentOs: Windows_NT_FullFramework
        pool:
          ${{ if eq(variables['System.TeamProject'], 'public') }}:
            name: NetCore-Svc-Public
            demands: ImageOverride -equals windows.vs2019.amd64.open
          ${{ if ne(variables['System.TeamProject'], 'public') }}:
            name: NetCore1ESPool-Svc-Internal
            demands: ImageOverride -equals windows.vs2019.amd64
        ${{ if eq(variables['System.TeamProject'], 'public') }}:
          helixTargetQueue: Windows.Amd64.VS2022.Pre.Open
        ${{ if ne(variables['System.TeamProject'], 'public') }}:
          helixTargetQueue: Windows.Amd64.VS2022.Pre
        strategy:
          matrix:
            Build_Debug:
              _BuildConfig: Debug
              _PublishType: none
              _SignType: test
              _Test: -test
            Build_Release:
              _BuildConfig: Release
              _PublishType: none
              _SignType: test
              _Test: -test

    - template: /eng/build.yml
      parameters:
        agentOs: Windows_NT_TestAsTools
        pool:
          ${{ if eq(variables['System.TeamProject'], 'public') }}:
            name: NetCore-Svc-Public
            demands: ImageOverride -equals windows.vs2019.amd64.open
          ${{ if ne(variables['System.TeamProject'], 'public') }}:
            name: NetCore1ESPool-Svc-Internal
            demands: ImageOverride -equals windows.vs2019.amd64
        strategy:
          matrix:
            Build_Debug:
              _BuildConfig: Debug
              _PublishType: none
              _SignType: test

    - template: /eng/build.yml
      parameters:
        agentOs: Ubuntu_18_04
        pool:
          ${{ if eq(variables['System.TeamProject'], 'public') }}:
            name: NetCore-Svc-Public
            demands: ImageOverride -equals Build.Ubuntu.1804.Amd64.Open
          ${{ if ne(variables['System.TeamProject'], 'public') }}:
            name: NetCore1ESPool-Svc-Internal
            demands: ImageOverride -equals Build.Ubuntu.1804.Amd64
        ${{ if eq(variables['System.TeamProject'], 'public') }}:
          helixTargetQueue: Ubuntu.1804.Amd64.Open
        ${{ if ne(variables['System.TeamProject'], 'public') }}:
          helixTargetQueue: Ubuntu.1804.Amd64
        strategy:
          matrix:
            Build_Debug:
              _BuildConfig: Debug
              _PublishType: none
              _SignType: test
            Build_Release:
              _BuildConfig: Release
              _PublishType: none
              _SignType: test

    - template: /eng/build.yml
      parameters:
        agentOs: Darwin
        pool:
          vmImage: 'macOS-latest'
        ${{ if eq(variables['System.TeamProject'], 'public') }}:
          helixTargetQueue: OSX.1015.Amd64.Open
        ${{ if ne(variables['System.TeamProject'], 'public') }}:
          helixTargetQueue: OSX.1015.Amd64
        strategy:
          matrix:
            Build_Debug:
              _BuildConfig: Debug
              _PublishType: none
              _SignType: test
            Build_Release:
              _BuildConfig: Release
              _PublishType: none
              _SignType: test

  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - template: /eng/common/templates/job/publish-build-assets.yml
      parameters:
        publishUsingPipelines: true
        dependsOn:
          - Windows_NT
        queue:
          name: NetCore1ESPool-Svc-Internal
          demands: ImageOverride -equals windows.vs2017.amd64
- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
  - template: /eng/common/templates/post-build/post-build.yml
    parameters:
      publishingInfraVersion: 3
      enableSymbolValidation: false
      enableSigningValidation: false
      enableNugetValidation: false
      enableSourceLinkValidation: false
      publishInstallersAndChecksums: true
      SDLValidationParameters:
        enable: false
        params: ' -SourceToolsList @("policheck","credscan")
        -TsaInstanceURL $(_TsaInstanceURL)
        -TsaProjectName $(_TsaProjectName)
        -TsaNotificationEmail $(_TsaNotificationEmail)
        -TsaCodebaseAdmin $(_TsaCodebaseAdmin)
        -TsaBugAreaPath $(_TsaBugAreaPath)
        -TsaIterationPath $(_TsaIterationPath)
        -TsaRepositoryName "dotnet-sdk"
        -TsaCodebaseName "dotnet-sdk"
        -TsaPublish $True'
