# Sample VSTS CI file
variables:
  Build.Repository.Clean: true
  targetFramework: netcoreapp2.0

trigger:
- master

# To be added in the future when VSTS supports this feature
# pr:
# - master

# Three phases for each of the three OSes we want to run on
phases:
  - phase: Windows_NT
    queue:
      name: Helix
      parallel: 99
      matrix:
        debug_configuration:
          _BuildConfig: Debug
        release_configuration:
          _BuildConfig: Release
    steps:
    - template: eng/build.yml

  - phase: OSX
    queue:
      name: Hosted macOS Preview
      parallel: 99
      matrix:
        debug_configuration:
          _BuildConfig: Debug
        release_configuration:
          _BuildConfig: Release
    steps:
    - template: eng/build.yml

  - phase: Linux
    queue:
      name: DotNetCore-Linux
      parallel: 99
      matrix:
        debug_configuration:
          _BuildConfig: Debug
        release_configuration:
          _BuildConfig: Release
    steps:
    - template: eng/build.yml