trigger:
- master
- release/*

variables:
  - name: teamName
    value: Roslyn-Project-System
  - name: PB_PublishBlobFeedUrl
    value: ''
  - name: _DotNetPublishToBlobFeed
    value: false
  - ${{ if ne(variables['System.TeamProject'], 'public') }}:
    - name: PB_PublishBlobFeedUrl
      value: https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
    - name: _DotNetPublishToBlobFeed
      value: true

jobs:
- template: /eng/build.yml
  parameters:
    agentOs: Windows_NT
    pool:
      ${{ if eq(variables['System.TeamProject'], 'public') }}:
        name: NetCorePublic-Int-Pool
        queue: buildpool.windows.10.amd64.vs2017.open
      ${{ if ne(variables['System.TeamProject'], 'public') }}:
        name: NetCoreInternal-Int-Pool
        queue: buildpool.windows.10.amd64.vs2017
    strategy:
      matrix:
        ${{ if eq(variables['System.TeamProject'], 'public') }}:
          Build_Debug:
            _BuildConfig: Debug
            _PublishType: none
            _SignType: test
        Build_Release:
          _BuildConfig: Release
          ${{ if eq(variables['System.TeamProject'], 'public') }}:
            _PublishType: none
            _SignType: test
          ${{ if ne(variables['System.TeamProject'], 'public') }}:
            _PublishType: blob
            _SignType: real

- template: /eng/build.yml
  parameters:
    agentOs: Windows_Perf
    pool:
      ${{ if eq(variables['System.TeamProject'], 'public') }}:
        name: NetCorePublic-Int-Pool
        queue: buildpool.windows.10.amd64.vs2017.open
      ${{ if ne(variables['System.TeamProject'], 'public') }}:
        name: Hosted VS2017
        queue: Windows.10.Amd64.ClientRS1.Perf # using a dedicated private Helix queue (perfsnakes)
    strategy:
      matrix:
        Build_Release:
          _BuildConfig: Release
          _PublishType: none
          _SignType: test

- template: /eng/build.yml
  parameters:
    agentOs: Linux_Perf
    pool:
      ${{ if eq(variables['System.TeamProject'], 'public') }}:
        name: Hosted Ubuntu 1604
      ${{ if ne(variables['System.TeamProject'], 'public') }}:
        name: Hosted Ubuntu 1604
        queue: Ubuntu.1604.Amd64.Perf # using a dedicated private Helix queue (perfsnakes)
    strategy:
      matrix:
        Build_Release:
          _BuildConfig: Release
          _PublishType: none
          _SignType: test

- ${{ if eq(variables['System.TeamProject'], 'public') }}:
  - template: /eng/build.yml
    parameters:
      agentOs: Windows_NT_FullFramework
      pool:
        name: NetCorePublic-Int-Pool
        queue: buildpool.windows.10.amd64.vs2017.open
      strategy:
        matrix:
          Build_Debug:
            _BuildConfig: Debug
            _PublishType: none
            _SignType: test
          Build_Release:
            _BuildConfig: Release
            _PublishType: none
            _SignType: test

  - template: /eng/build.yml
    parameters:
      agentOs: Windows_NT_TestAsTools
      pool:
        name: NetCorePublic-Int-Pool
        queue: buildpool.windows.10.amd64.vs2017.open
      strategy:
        matrix:
          Build_Debug:
            _BuildConfig: Debug
            _PublishType: none
            _SignType: test

  - template: /eng/build.yml
    parameters:
      agentOs: Ubuntu_14_04
      pool:
        name: Hosted Ubuntu 1604
      strategy:
        matrix:
          Build_Debug:
            _BuildConfig: Debug
            _PublishType: none
            _SignType: test
          Build_Release:
            _BuildConfig: Release
            _PublishType: none
            _SignType: test
      variables:
        _PREVIEW_VSTS_DOCKER_IMAGE: microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-cross-0cd4667-20170319080304

  - template: /eng/build.yml
    parameters:
      agentOs: Ubuntu_16_04
      pool:
        name: Hosted Ubuntu 1604
      strategy:
        matrix:
          Build_Debug:
            _BuildConfig: Debug
            _PublishType: none
            _SignType: test
          Build_Release:
            _BuildConfig: Release
            _PublishType: none
            _SignType: test
      variables:
        _PREVIEW_VSTS_DOCKER_IMAGE: microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-cross-e435274-20180628134544

  - template: /eng/build.yml
    parameters:
      agentOs: Darwin
      pool:
        name: DotNetCore-Mac
      strategy:
        matrix:
          Build_Debug:
            _BuildConfig: Debug
            _PublishType: none
            _SignType: test
          Build_Release:
            _BuildConfig: Release
            _PublishType: none
            _SignType: test

- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
  - template: /eng/common/templates/job/publish-build-assets.yml
    parameters:
      dependsOn:
        - Windows_NT
      queue:
        name: Hosted VS2017
