trigger:
  branches:
    include:
      - dnup
  paths:
    include:
      - src/Installer/dnup/
      - test/dnup.Tests/
      - global.json
      - .vsts-dnup-tests.yml

parameters:
- name: enableArm64Job
  displayName: Enables the ARM64 job
  type: boolean
  default: true

variables:

pr:
  branches:
    include:
      - dnup
      - main
  paths:
    include:
      - src/Installer/dnup/
      - test/dnup.Tests/
      - global.json
      - .vsts-dnup-tests.yml

variables:
  buildConfiguration: Release
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

stages:
- stage: dnup_tests
  displayName: dnup tests
  jobs:
  - template: /eng/pipelines/templates/jobs/dnup-tests.yml@self
    parameters:
      os: windows
      pool:
        name: $(DncEngPublicBuildPool)
        demands: ImageOverride -equals windows.vs2022.amd64.open
  - template: /eng/pipelines/templates/jobs/dnup-tests.yml@self
    parameters:
      os: linux
      pool:
        name: $(DncEngPublicBuildPool)
        demands: ImageOverride -equals build.ubuntu.2204.amd64.open
  - template: /eng/pipelines/templates/jobs/dnup-tests.yml@self
    parameters:
      os: macOS
      pool:
        name: Azure Pipelines
        vmImage: macOS-latest
