trigger:
  batch: true
  branches:
    include:
    - main
    - release/7.0.3xx
    - internal/release/*

pr:
  branches:
    include:
    - main
    - release/*
    - internal/release/*

variables:
  - name: _CIBuild
    value: -restore -build -sign -pack -ci
  - name: PostBuildSign
    value: true
  - ${{ if eq(variables['System.TeamProject'], 'public') }}:
    - name: _InternalRuntimeDownloadArgs
      value: ''
  - ${{ if ne(variables['System.TeamProject'], 'public') }}:
    - name: Codeql.Enabled
      value: true
    - name: _InternalRuntimeDownloadArgs
      value: /p:DotNetRuntimeSourceFeed=https://dotnetbuilds.blob.core.windows.net/internal 
        /p:DotNetRuntimeSourceFeedKey=$(dotnetbuilds-internal-container-read-token-base64)
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - group: DotNet-CLI-SDLValidation-Params
  # Set the MicroBuild plugin installation directory to the agent temp directory to avoid SDL tool scanning.
  - name: MicroBuildOutputFolderOverride
    value: $(Agent.TempDirectory)

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    sdl:
      sourceAnalysisPool:
        name: NetCore1ESPool-Svc-Internal
        image: 1es-windows-2022
        os: windows
    stages:
    - stage: build
      displayName: Build
      jobs:
      - job: Publish_Build_Configuration
        pool:
          ${{ if eq(variables['System.TeamProject'], 'public') }}:
            name: NetCore-Svc-Public
            image: 1es-windows-2019-open
            os: windows
          ${{ if eq(variables['System.TeamProject'], 'internal') }}:
            name: NetCore1ESPool-Svc-Internal
            image: 1es-windows-2019
            os: windows
        steps:
          - task: 1ES.PublishPipelineArtifact@1
            displayName: Publish Build Config
            inputs:
              targetPath: $(Build.SourcesDirectory)\eng\buildConfiguration
              artifactName: buildConfiguration
      - template: /eng/build.yml@self
        parameters:
          agentOs: Windows_NT
          pool:
            ${{ if eq(variables['System.TeamProject'], 'public') }}:
              name: NetCore-Svc-Public
              image: 1es-windows-2022-open
              os: windows
            ${{ if ne(variables['System.TeamProject'], 'public') }}:
              name: NetCore1ESPool-Svc-Internal
              image: 1es-windows-2022
              os: windows
          ${{ if eq(variables['System.TeamProject'], 'public') }}:
            helixTargetQueue: Windows.Amd64.VS2022.Pre.Open
          ${{ if ne(variables['System.TeamProject'], 'public') }}:
            helixTargetQueue: Windows.Amd64.VS2022.Pre
          variables:
          - name: _BuildConfig
            value: Release
          - name: _PublishArgs
            value: '-publish /p:DotNetPublishUsingPipelines=true'
          - ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
            - name: _SignType
              value: test
            - name: _Test
              value: -test
          - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
            - name: _SignType
              value: real
            - name: _Test
              value: ''
      - template: /eng/common/templates-official/job/source-build.yml@self
        parameters:
          enableInternalSources: true
          platform:
            name: 'Managed'
            container: 'mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7'
      - ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
        - template: /eng/build.yml@self
          parameters:
            agentOs: Windows_NT_FullFramework
            pool:
              ${{ if eq(variables['System.TeamProject'], 'public') }}:
                name: NetCore-Svc-Public
                demands: ImageOverride -equals windows.vs2022preview.amd64.open
              ${{ if ne(variables['System.TeamProject'], 'public') }}:
                name: NetCore1ESPool-Svc-Internal
                demands: ImageOverride -equals windows.vs2022preview.amd64
            ${{ if eq(variables['System.TeamProject'], 'public') }}:
              helixTargetQueue: Windows.Amd64.VS2022.Pre.Open
            ${{ if ne(variables['System.TeamProject'], 'public') }}:
              helixTargetQueue: Windows.Amd64.VS2022.Pre
            variables:
            - name: _BuildConfig
              value: Debug
            - name: _PublishArgs
              value: ''
            - name: _SignType
              value: test
            - name: _Test
              value: -test

        - template: /eng/build.yml@self
          parameters:
            agentOs: Windows_NT_TestAsTools
            pool:
              ${{ if eq(variables['System.TeamProject'], 'public') }}:
                name: NetCore-Svc-Public
                image: 1es-windows-2019-open
                os: windows
              ${{ if ne(variables['System.TeamProject'], 'public') }}:
                name: NetCore1ESPool-Svc-Internal
                image: 1es-windows-2019
                os: windows
            variables:
            - name: _BuildConfig
              value: Debug
            - name: _PublishArgs
              value: ''
            - name: _SignType
              value: test

        - template: /eng/build.yml@self
          parameters:
            agentOs: Ubuntu_20_04
            pool:
              ${{ if eq(variables['System.TeamProject'], 'public') }}:
                name: NetCore-Svc-Public
                image: 1es-ubuntu-2004-open
                os: linux
              ${{ if ne(variables['System.TeamProject'], 'public') }}:
                name: NetCore1ESPool-Svc-Internal
                image: 1es-ubuntu-2004
                os: linux
            ${{ if eq(variables['System.TeamProject'], 'public') }}:
              helixTargetQueue: Ubuntu.2004.Amd64.Open
            ${{ if ne(variables['System.TeamProject'], 'public') }}:
              helixTargetQueue: Ubuntu.2004.Amd64
            variables:
            - name: _BuildConfig
              value: Release
            - name: _PublishArgs
              value: ''
            - name: _SignType
              value: test
            - name: _Test
              value: -test

      - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
        - template: /eng/common/templates-official/job/publish-build-assets.yml@self
          parameters:
            publishUsingPipelines: true
            dependsOn:
              - Windows_NT
              - Source_Build_Managed
            pool:
              name: NetCore1ESPool-Svc-Internal
              image: 1es-windows-2019
              os: windows
    - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
      - template: /eng/common/templates-official/post-build/post-build.yml@self
        parameters:
          publishingInfraVersion: 3
          enableSymbolValidation: false
          enableSigningValidation: false
          enableNugetValidation: false
          enableSourceLinkValidation: false
          publishInstallersAndChecksums: true
          SDLValidationParameters:
            enable: false
            params: ' -SourceToolsList @("policheck","credscan")
            -TsaInstanceURL $(_TsaInstanceURL)
            -TsaProjectName $(_TsaProjectName)
            -TsaNotificationEmail $(_TsaNotificationEmail)
            -TsaCodebaseAdmin $(_TsaCodebaseAdmin)
            -TsaBugAreaPath $(_TsaBugAreaPath)
            -TsaIterationPath $(_TsaIterationPath)
            -TsaRepositoryName "dotnet-sdk"
            -TsaCodebaseName "dotnet-sdk"
            -TsaPublish $True'
