# Pipeline: https://dev.azure.com/dnceng-public/public/_build?definitionId=101

trigger: none

pr:
  branches:
    include:
    - main
    - release/*
    - internal/release/*
  paths:
    exclude:
    - documentation/*
    - README.md
    - CODEOWNERS

variables:
- template: /eng/pipelines/templates/variables/sdk-defaults.yml
# Variables used: DncEngPublicBuildPool
- template: /eng/common/templates/variables/pool-providers.yml

resources:
  containers:
  - container: alpine319WithNode
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.19-WithNode
  - container: centosStream9
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-stream9
  - container: debian12Amd64
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-gcc14-amd64
  - container: fedora39
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-39
  - container: ubuntu2204DebPkg
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-22.04-debpkg

stages:
############### BUILD STAGE ###############
- stage: build
  displayName: Build
  jobs:
  ############### WINDOWS ###############
  - template: /eng/pipelines/templates/jobs/sdk-job-matrix.yml@self
    parameters:
      pool:
        name: $(DncEngPublicBuildPool)
        demands: ImageOverride -equals windows.vs2022.amd64.open
        os: windows
      helixTargetQueue: windows.amd64.vs2022.pre.open

  ############### LINUX ###############
  - template: /eng/pipelines/templates/jobs/sdk-job-matrix.yml
    parameters:
      pool:
        name: $(DncEngPublicBuildPool)
        demands: ImageOverride -equals build.ubuntu.2204.amd64.open
        os: linux
      helixTargetQueue: ubuntu.2204.amd64.open

  ############### MACOS ###############
  - template: /eng/pipelines/templates/jobs/sdk-job-matrix.yml
    parameters:
      pool:
        name: Azure Pipelines
        vmImage: macOS-latest
        os: macOS
      helixTargetQueue: osx.13.amd64.open

  ############### SOURCE BUILD ###############
  - template: /eng/common/templates/job/source-build.yml@self
    parameters:
      platform:
        name: Managed
        container: centosStream9
        jobProperties:
          timeoutInMinutes: 30

  ############### DOTNET-FORMAT ###############
  - template: /eng/dotnet-format/dotnet-format-integration.yml
