// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Diagnostics;
using Microsoft.Dotnet.Installation.Internal;
using Microsoft.DotNet.Cli;
using Microsoft.DotNet.Cli.Utils;
using Microsoft.DotNet.Tools.Bootstrapper.Telemetry;
using Spectre.Console;

namespace Microsoft.DotNet.Tools.Bootstrapper;

internal class DotnetupProgram
{
    public static int Main(string[] args)
    {
        // Handle --debug flag using the standard .NET SDK pattern
        // This is DEBUG-only and removes the --debug flag from args
        DotnetupDebugHelper.HandleDebugSwitch(ref args);

        // Capture current console encoding so it can be restored on exit.
        // Uses the same AutomaticEncodingRestorer from the .NET SDK CLI.
        using AutomaticEncodingRestorer encodingRestorer = new();
        ConfigureConsoleEncoding();

        // Disable Spectre.Console line wrapping when output is redirected (piped),
        // since wrapping is not useful for non-interactive consumers.
        if (Console.IsOutputRedirected)
        {
            AnsiConsole.Profile.Width = int.MaxValue;
        }

        // Set up callback to notify user when waiting for another dotnetup process.
        // Write to stderr so piped stdout (e.g., print-env-script) is not corrupted.
        ScopedMutex.OnWaitingForMutex = () =>
        {
            Console.Error.WriteLine("Another dotnetup process is running. Waiting for it to finish...");
        };

        // Show first-run telemetry notice if needed
        FirstRunNotice.ShowIfFirstRun(DotnetupTelemetry.Instance.Enabled);

        // Start root activity for the entire process
        using var rootOp = DotnetupTelemetry.Instance.StartTrackedProcess("dotnetup");

        int processExitCode = 1;

        try
        {
            processExitCode = InvokeParser(args);

            return processExitCode;
        }
        catch (Exception ex)
        {
            DotnetupTelemetry.Instance.RecordException(rootOp.Activity, ex);

            // Log the error and return non-zero exit code
            Console.Error.WriteLine($"Error: {ex.Message}");
#if DEBUG
            Console.Error.WriteLine(ex.StackTrace);
#endif
            return 1;
        }
        finally
        {
            rootOp.SetTag(TelemetryTagNames.ExitCode, processExitCode);
            rootOp.SetStatus(processExitCode == 0 ? ActivityStatusCode.Ok : ActivityStatusCode.Error);
            rootOp.Dispose(); // emit process/complete event before flush
            DisposeTelemetry();
        }
    }

    private static int InvokeParser(string[] args)
    {
        return Parser.Invoke(args);
    }

    private static void DisposeTelemetry()
    {
        // Best-effort flush with a short timeout. The Azure Monitor exporter
        // has built-in offline storage (%LOCALAPPDATA%\Microsoft\AzureMonitor)
        // so unsent spans survive process exit and are retried on the next run.
        //
        // We intentionally skip Dispose(): TracerProvider.Dispose() internally
        // calls Shutdown() with its own (potentially long) timeout, which would
        // block the user noticeably. Since ThreadPool threads are background
        // threads, any remaining exporter work is terminated when Main returns.
        try
        {
            DotnetupTelemetry.Instance.WriteLogIfNecessary();
            DotnetupTelemetry.Instance.Flush(timeoutMilliseconds: 5000);
        }
        catch
        {
            // Telemetry should never delay or crash the process exit.
        }
    }

    /// <summary>
    /// Sets the console output encoding to UTF-8 so Unicode glyphs render correctly.
    /// Uses UILanguageOverride.OperatingSystemSupportsUtf8() from the .NET SDK CLI.
    /// </summary>
    private static void ConfigureConsoleEncoding()
    {
        if (Environment.GetEnvironmentVariable("DOTNET_CLI_CONSOLE_USE_DEFAULT_ENCODING") != "1"
            && UILanguageOverride.OperatingSystemSupportsUtf8())
        {
            // Use UTF-8 without BOM to prevent corrupting piped output.
            // Encoding.UTF8 has encoderShouldEmitUTF8Identifier=true, which causes the
            // runtime to write a 3-byte BOM (0xEF 0xBB 0xBF) to stdout when the encoding
            // is first applied. This corrupts scripts generated by print-env-script when
            // output is redirected to a file (e.g., `dotnetup print-env-script > env.sh`).
            Console.OutputEncoding = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false);
        }
    }
}
