<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(SdkTargetFramework)</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Nullable>enable</Nullable>
    <StrongNameKeyId>MicrosoftAspNetCore</StrongNameKeyId>
    <IsPackable>false</IsPackable>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="dotnet" />
    <InternalsVisibleTo Include="dotnet-aot" />
    <InternalsVisibleTo Include="dotnet.Tests" />
    <InternalsVisibleTo Include="dotnet-aot.Tests" />
  </ItemGroup>
</Project>
