// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "type", Target = "~T:Microsoft.NET.Build.Containers.Tasks.DownloadContainerManifest")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "type", Target = "~T:Microsoft.NET.Build.Containers.IMultiImageManifest")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "type", Target = "~T:Microsoft.NET.Build.Containers.ISingleImageManifest")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "member", Target = "~P:Microsoft.NET.Build.Containers.IPlatformSpecificManifestData.digest")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "member", Target = "~P:Microsoft.NET.Build.Containers.IPlatformSpecificManifestData.mediaType")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "member", Target = "~P:Microsoft.NET.Build.Containers.IPlatformSpecificManifestData.platform")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "member", Target = "~P:Microsoft.NET.Build.Containers.IPlatformSpecificManifestData.size")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "type", Target = "~T:Microsoft.NET.Build.Containers.IPlatformSpecificManifestData")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "type", Target = "~T:Microsoft.NET.Build.Containers.ImageIndexV1")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "type", Target = "~T:Microsoft.NET.Build.Containers.ManifestListV2")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "type", Target = "~T:Microsoft.NET.Build.Containers.IManifest")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.NET.Build.Containers.RidMapping.CreateRidForPlatform(Microsoft.NET.Build.Containers.PlatformInformation)~System.String")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.NET.Build.Containers.RidMapping.GetManifestsByRid(Microsoft.NET.Build.Containers.PlatformSpecificManifest[])~System.Collections.Generic.IReadOnlyDictionary{System.String,Microsoft.NET.Build.Containers.PlatformSpecificManifest}")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.NET.Build.Containers.RidMapping.GetManifestsByRid(Microsoft.NET.Build.Containers.PlatformSpecificOciManifest[])~System.Collections.Generic.IReadOnlyDictionary{System.String,Microsoft.NET.Build.Containers.PlatformSpecificOciManifest}")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "type", Target = "~T:Microsoft.NET.Build.Containers.RidMapping")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.NET.Build.Containers.Tasks.DownloadLayers.Cancel")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.NET.Build.Containers.Tasks.DownloadLayers.Execute~System.Boolean")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.NET.Build.Containers.Tasks.DownloadLayers.ExecuteAsync~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "member", Target = "~P:Microsoft.NET.Build.Containers.Tasks.DownloadLayers.ContentStore")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "member", Target = "~P:Microsoft.NET.Build.Containers.Tasks.DownloadLayers.Registry")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "member", Target = "~P:Microsoft.NET.Build.Containers.Tasks.DownloadLayers.Repository")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "type", Target = "~T:Microsoft.NET.Build.Containers.Tasks.DownloadLayers")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.NET.Build.Containers.Tasks.SelectRuntimeIdentifierSpecificItems.Cancel")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.NET.Build.Containers.Tasks.SelectRuntimeIdentifierSpecificItems.Execute~System.Boolean")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.NET.Build.Containers.Tasks.SelectRuntimeIdentifierSpecificItems.ExecuteAsync~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "member", Target = "~P:Microsoft.NET.Build.Containers.Tasks.SelectRuntimeIdentifierSpecificItems.Items")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "member", Target = "~P:Microsoft.NET.Build.Containers.Tasks.SelectRuntimeIdentifierSpecificItems.RuntimeIdentifierGraphPath")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "member", Target = "~P:Microsoft.NET.Build.Containers.Tasks.SelectRuntimeIdentifierSpecificItems.SelectedItems")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "member", Target = "~P:Microsoft.NET.Build.Containers.Tasks.SelectRuntimeIdentifierSpecificItems.TargetRuntimeIdentifier")]
[assembly: SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API", Justification = "<Pending>", Scope = "type", Target = "~T:Microsoft.NET.Build.Containers.Tasks.SelectRuntimeIdentifierSpecificItems")]
