<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(CurrentTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SelfContained>false</SelfContained>
    <UseAppHost>true</UseAppHost>
    <AppHostDotNetSearch>AppRelative</AppHostDotNetSearch>
  </PropertyGroup>
</Project>