parameters:
  ### GENERAL ###
  variables: {}
  dependsOn: ''
  # helixTargetQueue: ''
  oneESCompat:
    templateFolderName: templates
    publishTaskPrefix: ''
  # container: ''
  # helixTargetContainer: ''
  categoryName: dnup
  # runTests: true
  # publishRetryConfig: false
  # publishXunitResults: false
  # enableSbom: true
  # timeoutInMinutes: 150

jobs:
# - template: /eng/common/${{ parameters.oneESCompat.templateFolderName }}/job/job.yml
- deployment: PublishPackages
  displayName: '🚀 Publish dnup library packages'
  environment: DotNet-SDK-Workloads
  pool:
    name: $(DncEngInternalBuildPool)
    image: 1es-windows-2022
    os: windows
  templateContext:
    type: releaseJob
    isProduction: true
  strategy:
    runOnce:
      deploy:
        steps:
          # 1ES docs: https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/inputs
          - task: 1ES.DownloadPipelineArtifact@1
            displayName: 🟣 Download build artifacts
            inputs:
              artifactName: dnup-library-packages
              targetPath: $(System.DefaultWorkingDirectory)/artifacts
          - powershell: |
              & Get-ChildItem -Path $(System.DefaultWorkingDirectory)/artifacts -Recurse -File | Select-Object -ExpandProperty FullName
          # 1ES docs: https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/outputs/nuget-packages
          # DotNetCoreCLI@2 docs: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/dotnet-core-cli-v2
          - ${{ if eq(true, true) }}:
            - task: 1ES.PublishNuget@1
              displayName: 🟣 Publish packages to AzDO
              inputs:
                useDotNetTask: true
                packagesToPush: $(System.DefaultWorkingDirectory)/artifacts/**/*.nupkg
                packageParentPath: $(System.DefaultWorkingDirectory)/artifacts
                publishVstsFeed: public/dotnet-tools