name: Ensure Trusted Commenter
description: Fails if the comment author is not a trusted collaborator.
inputs:
  author-association:
    description: GitHub author association for the triggering comment.
    required: true
runs:
  using: composite
  steps:
    - name: Verify commenter
      shell: bash
      env:
        AUTHOR_ASSOCIATION: ${{ inputs.author-association }}
      run: |
        case "${AUTHOR_ASSOCIATION}" in
          MEMBER|OWNER|COLLABORATOR)
            exit 0
            ;;
          *)
            echo "Only trusted collaborators can trigger this workflow." >&2
            exit 1
            ;;
        esac
