<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(SdkTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <ExcludeFromSourceOnlyBuild>true</ExcludeFromSourceOnlyBuild>
    <IsPackable>false</IsPackable>
    <!-- The runtime requires the startup hook type to be named StartupHook in the global namespace. -->
    <NoWarn>$(NoWarn);CA1050</NoWarn>
  </PropertyGroup>

</Project>
