<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="MSTest.Sdk">

  <PropertyGroup>
    <EnableDefaultItems>false</EnableDefaultItems>
    <OutDirName>Tests\$(MSBuildProjectName)</OutDirName>
    <PackageId>testSdkILLink</PackageId>
    <TargetFramework>$(SdkTargetFramework)</TargetFramework>
    <MSTestParallelizeScope>ClassLevel</MSTestParallelizeScope>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Reflection.MetadataLoadContext" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microsoft.NET.TestFramework.MSTest\Microsoft.NET.TestFramework.MSTest.csproj" />
    <ProjectReference Include="..\TelemetryStdOutLogger\TelemetryStdOutLogger.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="**\*.cs" Exclude="$(GlobalExclude)" />
    <Compile Include="..\Microsoft.NET.Publish.Tests\PublishTestUtils.cs" LinkBase="Shared" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\src\Tasks\Common\Resources\Strings.resx" LinkBase="Resources" GenerateSource="True" Namespace="Microsoft.NET.Build.Tasks" />
    <PackageReference Include="Microsoft.DotNet.XliffTasks" Version="$(MicrosoftDotNetXliffTasksPackageVersion)" PrivateAssets="all" IsImplicitlyDefined="true" />
  </ItemGroup>

</Project>
