# This is the main build definition (PR+CI) for dotnet/dotnet

trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
    - internal/release/*
    exclude:
    - release/*.0.2xx
    - release/*.0.3xx
    - release/*.0.4xx
    - internal/release/*.0.2xx
    - internal/release/*.0.3xx
    - internal/release/*.0.4xx

pr:
  branches:
    include:
    - main
    - release/*
    - internal/release/*

stages:
- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
  - template: templates/stages/vmr-scan.yml

- template: /src/installer/eng/pipelines/templates/stages/vmr-build.yml
  parameters:
    isBuiltFromVmr: true
