# This yml is used by these pipelines and triggers:
#
# - dotnet-source-build (internal)
#   https://dev.azure.com/dnceng/internal/_build?definitionId=1219
#   - CI: release/* and internal/release/* only, every batched commit, full build

trigger:
  batch: true
  branches:
    include:
    - release/9.0.1xx
    - internal/release/9.0.1xx

variables:
# enable source-only build for pipelines that contain the -source-build string
- name: isSourceOnlyBuild
  value: ${{ contains(variables['Build.DefinitionName'], '-source-build') }}

- name: isScheduleTrigger
  value: ${{ eq(variables['Build.Reason'], 'Schedule') }}

- name: isPRTrigger
  value: ${{ eq(variables['Build.Reason'], 'PullRequest') }}

- template: /eng/common/templates-official/variables/pool-providers.yml@self

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: $(DncEngInternalBuildPool)
        image: 1es-windows-2022
        os: windows

      # Spotbugs is failing the Windows builds: https://github.com/dotnet/dnceng/issues/2740
      spotBugs:
        enabled: false

      codeql:
        compiled:
          enabled: true
        # Runs analysis in the SDL stage and not every job
        # https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/sdlanalysis/codeql#improving-codeql-performance
        runSourceLanguagesInSourceAnalysis: true

      baseline:
        baselineFile: $(Build.SourcesDirectory)\.config\guardian\.gdnbaselines

    stages:
    - ${{ if and(ne(variables.isPRTrigger, 'true'), eq(variables['System.TeamProject'], 'internal')) }}:
      - template: /eng/pipelines/templates/stages/vmr-scan.yml@self

    - template: /src/sdk/eng/pipelines/templates/stages/vmr-build.yml@self
      parameters:
        isBuiltFromVmr: true
        isSourceOnlyBuild: ${{ variables.isSourceOnlyBuild }}
        ${{ if eq(variables.isScheduleTrigger, 'true') }}:
          scope: full
        ${{ elseif eq(variables.isPRTrigger, 'true') }}:
          scope: lite
        ${{ else }}:
          scope: full
