# This is the non-1ES PR pipeline for dotnet/dotnet
# https://dev.azure.com/dnceng-public/public/_build?definitionId=240

trigger:
  batch: true
  branches:
    include:
    - release/9.0.1xx

pr:
  branches:
    include:
    - release/9.0.1xx

variables:
# enable source-only build for pipelines that contain the -source-build string
- name: isSourceOnlyBuild
  value: ${{ contains(variables['Build.DefinitionName'], '-source-build') }}

- name: isScheduleTrigger
  value: ${{ eq(variables['Build.Reason'], 'Schedule') }}

- name: isPRTrigger
  value: ${{ eq(variables['Build.Reason'], 'PullRequest') }}

- name: Codeql.Enabled  # we run CodeQL on internal builds only
  value: false

- template: /eng/common/templates/variables/pool-providers.yml@self

stages:
- template: /src/sdk/eng/pipelines/templates/stages/vmr-build.yml
  parameters:
    isBuiltFromVmr: true
    isSourceOnlyBuild: ${{ variables.isSourceOnlyBuild }}
    ${{ if eq(variables.isScheduleTrigger, 'true') }}:
      scope: full
    ${{ elseif eq(variables.isPRTrigger, 'true') }}:
      scope: lite
    ${{ else }}:
      scope: full
