<Project Sdk="MSTest.Sdk">

  <PropertyGroup>
    <TargetFramework>$(SdkTargetFramework)</TargetFramework>
    <RootNamespace>Microsoft.DotNet.Cli.Resources.Generator.Tests</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.CodeAnalysis.ResxSourceGenerator"
                      GeneratePathProperty="true"
                      PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <PackageDownload Include="Microsoft.NETFramework.ReferenceAssemblies.net472" Version="[1.0.3]" />

    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>ResxSourceGeneratorPackagePath</_Parameter1>
      <_Parameter2>$(PkgMicrosoft_CodeAnalysis_ResxSourceGenerator)</_Parameter2>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>NuGetPackageRoot</_Parameter1>
      <_Parameter2>$(NuGetPackageRoot)</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Cli\Microsoft.DotNet.Cli.Resources.Generator\Microsoft.DotNet.Cli.Resources.Generator.csproj" />
    <ProjectReference Include="..\..\src\Cli\Microsoft.DotNet.Cli.CoreUtils\Microsoft.DotNet.Cli.CoreUtils.csproj" />
  </ItemGroup>

</Project>
