# Licensed to the .NET Foundation under one or more agreements.
# The .NET Foundation licenses this file to you under the MIT license.

# Explicit maintenance command, never invoked by the build.
$ErrorActionPreference = 'Stop'
$resources = Join-Path $PSScriptRoot 'Resources'
foreach ($name in @('CliStrings', 'CliCommandStrings')) {
    $sourceDirectory = if ($name -eq 'CliStrings') {
        Join-Path $PSScriptRoot '..\dotnet'
    } else {
        Join-Path $PSScriptRoot '..\dotnet\Commands'
    }
    [xml]$source = Get-Content (Join-Path $sourceDirectory "$name.resx") -Raw
    $keys = @(Get-Content (Join-Path $resources "$name.keys") |
        Where-Object { $_.Trim() -and !$_.StartsWith('#') })
    foreach ($key in $keys) {
        if ($key -cnotin @($source.root.data | ForEach-Object { $_.name })) {
            throw "Unknown $name resource key: $key"
        }
    }
    $inputs = @($null) + @(Get-ChildItem (Join-Path $sourceDirectory "xlf\$name.*.xlf"))
    foreach ($inputFile in $inputs) {
        $document = [System.Xml.XmlDocument]::new()
        $root = $document.CreateElement('root')
        [void]$document.AppendChild($root)
        [void]$root.AppendChild($document.CreateComment(' Generated by GenerateResources.ps1. Do not edit. '))
        foreach ($header in $source.root.resheader) {
            [void]$root.AppendChild($document.ImportNode($header, $true))
        }
        $translations = @{}
        $culture = ''
        if ($inputFile) {
            [xml]$xlf = Get-Content $inputFile.FullName -Raw
            $culture = '.' + $xlf.xliff.file.'target-language'
            foreach ($unit in $xlf.xliff.file.body.'trans-unit') {
                if ($unit.target -and $unit.target.state -ne 'new') {
                    $translations[$unit.id] = $unit.target.InnerText
                }
            }
        }
        foreach ($entry in $source.root.data) {
            if ($entry.name -cin $keys) {
                $copy = $document.ImportNode($entry, $true)
                if ($translations.ContainsKey($entry.name)) {
                    $copy.SelectSingleNode('value').InnerText = $translations[$entry.name]
                }
                [void]$root.AppendChild($copy)
            }
        }
        $settings = [System.Xml.XmlWriterSettings]::new()
        $settings.Indent = $true
        $settings.Encoding = [System.Text.UTF8Encoding]::new($false)
        $settings.NewLineChars = "`n"
        $writer = [System.Xml.XmlWriter]::Create((Join-Path $resources "$name$culture.resx"), $settings)
        try { $document.Save($writer) } finally { $writer.Dispose() }
    }
}
