name: dotnet-sdk
version: 8.0.100-preview.5.23303.2
summary: Cross-Platform .NET Core SDK
description: |
  .NET Core SDK. https://dot.net/core.

architectures:
  - build-on: amd64
    run-on: amd64

grade: stable
confinement: classic
base: core20

parts:
  dotnet-sdk:
      plugin: dump
      source: https://download.visualstudio.microsoft.com/download/pr/07b027f8-4ef8-48cb-becc-132652c625bb/441ef662adfe931013745df24d53b26d/dotnet-sdk-8.0.100-preview.5.23303.2-linux-x64.tar.gz
      source-checksum: sha512/dfe2085a92854a5cee84cb7be9344368f5dcb6333c4ca215375a34b862f3a3ee66c953b9957f7b46f6cd710992ee038f6b4c2bd16464b4a216a1785868e86f7c
      stage-packages:
      - libicu66
      - libgcc1
      - libstdc++6
      - libssl1.1
      - libcurl4
      - libgssapi-krb5-2
      - zlib1g
      - lldb
      - libunwind8
      - libtinfo5
      - liblttng-ust0
      - liburcu6

  runtime-wrapper:
      plugin: dump
      source: .

apps:
  dotnet:
    command: dotnet
