<!--
Licensed to the .NET Foundation under one or more agreements.
The .NET Foundation licenses this file to you under the MIT license.
-->
<Project>
  <PropertyGroup>
    <_ProjectDataTaskAssembly>$(MSBuildThisFileDirectory)Host.ProjectData.Tasks.dll</_ProjectDataTaskAssembly>
  </PropertyGroup>
  <Target Name="ProjectDataBuild">
    <WriteLinesToFile File="$(MSBuildProjectDirectory)/host-projectdata.txt"
                      Lines="$(_ProjectDataTaskAssembly)"
                      Overwrite="true" />
  </Target>
</Project>
