parameters:
  # Agent OS identifier and used as job name
  agentOs: ''

  # Agent pool
  pool: {}

  # Additional variables
  variables: {}

  # Build strategy - matrix
  strategy: ''

  # Job timeout
  timeoutInMinutes: 180

jobs:
- template: /eng/common/templates/job/job.yml
  parameters:
    name: ${{ parameters.agentOs }}
    enableMicrobuild: true
    enablePublishBuildAssets: true
    enableTelemetry: true
    enablePublishUsingPipelines: true
    helixRepo: dotnet/sdk
    pool: ${{ parameters.pool }}
    timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    ${{ if ne(parameters.strategy, '') }}:
      strategy: ${{ parameters.strategy }}
    workspace:
      clean: all
    variables:
      - ${{ insert }}: ${{ parameters.variables }}
      - _AgentOSName: ${{ parameters.agentOs }}
      - _TeamName: DotNetCore
      - _OfficialBuildIdArgs: ''
      - _PublishArgs: ''
      - _SignArgs: ''
      - _TestArgs: $(_Test)
      - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
        - group: DotNet-Symbol-Server-PATs
        - group: DotNet-HelixApi-Access
        - group: dotnet-benchview
        - group: DotNet-Blob-Feed
        - _OfficialBuildIdArgs: /p:OfficialBuildId=$(BUILD.BUILDNUMBER)
        - _PublishArgs: /p:DotNetPublishBlobFeedKey=$(dotnetfeed-storage-access-key-1)
                    /p:DotNetPublishBlobFeedUrl=$(PB_PublishBlobFeedUrl)
                    /p:DotNetPublishToBlobFeed=$(_DotNetPublishToBlobFeed)
                    /p:DotNetSymbolServerTokenMsdl=$(microsoft-symbol-server-pat)
                    /p:DotNetSymbolServerTokenSymWeb=$(symweb-symbol-server-pat)
                    /p:PB_PublishType=$(_PublishType)
                    /p:DotNetPublishUsingPipelines=true
        - _SignArgs: /p:DotNetSignType=$(_SignType) /p:TeamName=$(_TeamName)
        - _PerfIterations: 25
    steps:
    - ${{ if eq(parameters.agentOs, 'Windows_NT') }}:
      - ${{ if ne(variables['System.TeamProject'], 'public') }}:
        - task: PowerShell@2
          displayName: Setup Private Feeds Credentials
          inputs:
            filePath: $(Build.SourcesDirectory)/eng/common/SetupNugetSources.ps1
            arguments: -ConfigFile $(Build.SourcesDirectory)/NuGet.config -Password $Env:Token
          env:
            Token: $(dn-bot-dnceng-artifact-feeds-rw)
      - script: eng\CIBuild.cmd
                  -configuration $(_BuildConfig)
                  $(_PublishArgs)
                  $(_SignArgs)
                  $(_OfficialBuildIdArgs)
                  $(_TestArgs)
        displayName: Build
        env:
          BuildConfig: $(_BuildConfig)
          BlobFeedUrl: $(PB_PublishBlobFeedUrl)
          PublishType: $(_PublishType)

    - ${{ if eq(parameters.agentOs, 'Windows_NT_FullFramework') }}:
      - ${{ if ne(variables['System.TeamProject'], 'public') }}:
        - task: PowerShell@2
          displayName: Setup Private Feeds Credentials
          inputs:
            filePath: $(Build.SourcesDirectory)/eng/common/SetupNugetSources.ps1
            arguments: -ConfigFile $(Build.SourcesDirectory)/NuGet.config -Password $Env:Token
          env:
            Token: $(dn-bot-dnceng-artifact-feeds-rw)
      - script: eng\common\CIBuild.cmd
                  -configuration $(_BuildConfig)
                  $(_PublishArgs)
                  $(_SignArgs)
                  $(_OfficialBuildIdArgs)
        displayName: Build
        env:
          BuildConfig: $(_BuildConfig)
          BlobFeedUrl: $(PB_PublishBlobFeedUrl)
          PublishType: $(_PublishType)
          TestFullMSBuild: 'true'

    - ${{ if eq(parameters.agentOs, 'Windows_NT_TestAsTools') }}:
      - ${{ if ne(variables['System.TeamProject'], 'public') }}:
        - task: PowerShell@2
          displayName: Setup Private Feeds Credentials
          inputs:
            filePath: $(Build.SourcesDirectory)/eng/common/SetupNugetSources.ps1
            arguments: -ConfigFile $(Build.SourcesDirectory)/NuGet.config -Password $Env:Token
          env:
            Token: $(dn-bot-dnceng-artifact-feeds-rw)
      - script: eng\common\CIBuild.cmd
                  -configuration $(_BuildConfig)
                  $(_PublishArgs)
                  $(_SignArgs)
                  $(_OfficialBuildIdArgs)
                  /p:RunTestsAsTool=true
        displayName: Build
        env:
          BuildConfig: $(_BuildConfig)
          BlobFeedUrl: $(PB_PublishBlobFeedUrl)
          PublishType: $(_PublishType)

    - ${{ if notIn(parameters.agentOs, 'Windows_NT', 'Windows_NT_FullFramework', 'Windows_NT_TestAsTools') }}:
      - ${{ if ne(variables['System.TeamProject'], 'public') }}:
        - task: Bash@3
          displayName: Setup Private Feeds Credentials
          inputs:
            filePath: $(Build.SourcesDirectory)/eng/common/SetupNugetSources.sh
            arguments: $(Build.SourcesDirectory)/NuGet.config $Token
          env:
            Token: $(dn-bot-dnceng-artifact-feeds-rw)
      - script: eng/common/cibuild.sh 
                  --configuration $(_BuildConfig)
                  $(_PublishArgs)
                  $(_SignArgs)
                  $(_OfficialBuildIdArgs)
        displayName: Build
        env:
          BuildConfig: $(_BuildConfig)
          BlobFeedUrl: $(PB_PublishBlobFeedUrl)
          PublishType: $(_PublishType)

    - task: PublishTestResults@1  
      displayName: Publish Test Results 
      inputs: 
        testRunner: XUnit 
        testResultsFiles: 'artifacts/TestResults/$(_BuildConfig)/*.xml' 
        testRunTitle: '$(_AgentOSName)_$(Agent.JobName)'  
        platform: '$(BuildPlatform)'  
        configuration: '$(_BuildConfig)'  
      condition: not(succeeded())

    - task: CopyFiles@2 
      displayName: Gather Logs  
      inputs: 
        SourceFolder: '$(Build.SourcesDirectory)/artifacts' 
        Contents: | 
         log/$(_BuildConfig)/**/* 
         TestResults/$(_BuildConfig)/**/* 
         SymStore/$(_BuildConfig)/**/*
        TargetFolder: '$(Build.ArtifactStagingDirectory)' 
      continueOnError: true 
      condition: always()

    - task: PublishBuildArtifacts@1 
      displayName: Publish Logs to VSTS 
      inputs: 
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'  
        ArtifactName: '$(_AgentOSName)_$(Agent.JobName)_$(Build.BuildNumber)' 
        publishLocation: Container  
      continueOnError: true 
      condition: always()
