parameters:
  # Agent OS identifier and used as job name
  agentOs: ''

  # Agent pool
  pool: {}

  # Additional variables
  variables: {}

  # Build strategy - matrix
  strategy: ''

  # Job timeout
  timeoutInMinutes: 120

jobs:
- template: /eng/common/templates/job/job.yml
  parameters:
    name: ${{ parameters.agentOs }}
    enableMicrobuild: true
    enablePublishBuildArtifacts: true
    enablePublishBuildAssets: true
    enablePublishTestResults: true
    enableTelemetry: true
    helixRepo: dotnet/sdk
    pool: ${{ parameters.pool }}
    timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    ${{ if ne(parameters.strategy, '') }}:
      strategy: ${{ parameters.strategy }}
    variables: 
      - ${{ insert }}: ${{ parameters.variables }}
      - _AgentOSName: ${{ parameters.agentOs }}
      - _TeamName: DotNetCore
      - _PerformanceArgs: ''
      - _OfficialBuildIdArgs: ''
      - _PublishArgs: ''
      - _SignArgs: ''
      - ${{ if ne(variables['System.TeamProject'], 'public') }}:
        - group: DotNet-Symbol-Server-PATs
        - group: DotNet-HelixApi-Access
        - group: DotNet-Blob-Feed
        - _OfficialBuildIdArgs: /p:OfficialBuildId=$(BUILD.BUILDNUMBER)
        - _PublishArgs: /p:DotNetPublishBlobFeedKey=$(dotnetfeed-storage-access-key-1)
                    /p:DotNetPublishBlobFeedUrl=$(PB_PublishBlobFeedUrl)
                    /p:DotNetPublishToBlobFeed=$(_DotNetPublishToBlobFeed)
                    /p:DotNetSymbolServerTokenMsdl=$(microsoft-symbol-server-pat)
                    /p:DotNetSymbolServerTokenSymWeb=$(symweb-symbol-server-pat)
                    /p:PB_PublishType=$(_PublishType)
        - _SignArgs: /p:DotNetSignType=$(_SignType) /p:TeamName=$(_TeamName)
        - _PerformanceArgs: /p:PerfIterations=10

    steps:
    - ${{ if eq(parameters.agentOs, 'Windows_NT') }}:
      - script: eng\common\CIBuild.cmd
                  -configuration $(_BuildConfig)
                  $(_PublishArgs)
                  $(_SignArgs)
                  $(_OfficialBuildIdArgs)
        displayName: Build
        env:
          BuildConfig: $(_BuildConfig)
          BlobFeedUrl: $(PB_PublishBlobFeedUrl)
          PublishType: $(_PublishType)

    - ${{ if eq(parameters.agentOs, 'Windows_NT_FullFramework') }}:
      - script: eng\common\CIBuild.cmd
                  -configuration $(_BuildConfig)
                  $(_PublishArgs)
                  $(_SignArgs)
                  $(_OfficialBuildIdArgs)
        displayName: Build
        env:
          BuildConfig: $(_BuildConfig)
          BlobFeedUrl: $(PB_PublishBlobFeedUrl)
          PublishType: $(_PublishType)
          TestFullMSBuild: 'true'

    - ${{ if eq(parameters.agentOs, 'Windows_NT_TestAsTools') }}:
      - script: eng\common\CIBuild.cmd
                  -configuration $(_BuildConfig)
                  $(_PublishArgs)
                  $(_SignArgs)
                  $(_OfficialBuildIdArgs)
                  /p:RunTestsAsTool=true
        displayName: Build
        env:
          BuildConfig: $(_BuildConfig)
          BlobFeedUrl: $(PB_PublishBlobFeedUrl)
          PublishType: $(_PublishType)

    - ${{ if eq(parameters.agentOs, 'Windows_Perf') }}:
      - script: build.cmd
                  -configuration $(_BuildConfig)
                  -ci -msbuildEngine dotnet
                  -performanceTest
                  $(_PerformanceArgs)
        displayName: Build
        timeoutInMinutes: 240
        env:
          BuildConfig: $(_BuildConfig)
    - ${{ if and(eq(parameters.agentOs, 'Windows_Perf'), ne(variables['System.TeamProject'], 'public')) }}:
      - script: build\uploadperftobenchview.cmd
        displayName: Upload to BenchView
        env: 
          perfWorkingDirectory: $(Build.SourcesDirectory)\artifacts\TestResults\$(_BuildConfig)\Performance
          configuration: $(_BuildConfig)
          runType: "rolling"
          architecture: x64
          GIT_COMMIT: $(Build.SourceVersion)
          GIT_BRANCH: $(Build.SourceBranchName)

    - ${{ if eq(parameters.agentOs, 'Linux_Perf') }}:
      - script: ./build.sh
                  --configuration $(_BuildConfig)
                  --ci --performancetest
                  $(_PerformanceArgs)
        displayName: Build
        timeoutInMinutes: 240
        env:
          BuildConfig: $(_BuildConfig)
    - ${{ if and(eq(parameters.agentOs, 'Linux_Perf'), ne(variables['System.TeamProject'], 'public')) }}:
      - script: build/uploadperftobenchview.sh
        displayName: Upload to BenchView
        env: 
          perfWorkingDirectory: $(Build.SourcesDirectory)/artifacts/TestResults/$(_BuildConfig)/Performance
          configuration: $(_BuildConfig)
          runType: "rolling"
          architecture: x64
          GIT_COMMIT: $(Build.SourceVersion)
          GIT_BRANCH: $(Build.SourceBranchName)

    - ${{ if notIn(parameters.agentOs, 'Windows_NT', 'Windows_NT_FullFramework', 'Windows_NT_TestAsTools', 'Windows_Perf', 'Linux_Perf') }}:
      - script: eng/common/cibuild.sh
                  --configuration $(_BuildConfig)
                  $(_PublishArgs)
                  $(_SignArgs)
                  $(_OfficialBuildIdArgs)
        displayName: Build
        env:
          BuildConfig: $(_BuildConfig)
          BlobFeedUrl: $(PB_PublishBlobFeedUrl)
          PublishType: $(_PublishType)
