<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(SdkTargetFramework)</TargetFramework>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <CopyBuildOutputToPublishDirectory>false</CopyBuildOutputToPublishDirectory>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.ProjectData.Tasks" GeneratePathProperty="true" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="$(PkgMicrosoft_NET_ProjectData_Tasks)/lib/netstandard2.0/Microsoft.NET.ProjectData.Schema.props;
                      $(PkgMicrosoft_NET_ProjectData_Tasks)/lib/netstandard2.0/Microsoft.NET.ProjectData.targets"
             Link="%(Filename)%(Extension)"
             CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
