<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(RepoRoot)src\Cli\Microsoft.DotNet.Cli.Resources.Generator\Microsoft.DotNet.Cli.Resources.Generator.props" />
  <PropertyGroup>
    <TargetFramework>$(SdkTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Nullable>enable</Nullable>
    <StrongNameKeyId>MicrosoftAspNetCore</StrongNameKeyId>
    <IsPackable>true</IsPackable>
    <DefineConstants>$(DefineConstants);FILE_BASED_PROGRAMS_PUBLIC;FILE_BASED_PROGRAMS_SYSTEM_TEXT_JSON</DefineConstants>

    <!--
      Mark as Native AOT compatible. This will enable relevant analyzers.
      https://learn.microsoft.com/dotnet/core/deploying/native-aot/#aot-compatibility-analyzers
    -->
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources.resx" LinkBase="Resources" GenerateSource="true" Generator="Microsoft.DotNet.Cli.Resources" Namespace="Microsoft.DotNet.ProjectTools" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Condition=" '$(DotNetBuildSourceOnly)' != 'true' ">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cli\Microsoft.DotNet.Cli.CoreUtils\Microsoft.DotNet.Cli.CoreUtils.csproj" />
    <ProjectReference Include="..\Cli\Microsoft.DotNet.Cli.Resources.Generator\Microsoft.DotNet.Cli.Resources.Generator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"
                      PrivateAssets="all" />
    <InternalsVisibleTo Include="dotnet" />
    <InternalsVisibleTo Include="dotnet-aot" />
    <InternalsVisibleTo Include="dotnet-aot.Tests" />
    <InternalsVisibleTo Include="Microsoft.DotNet.HotReload.Watch" />
    <InternalsVisibleTo Include="dotnet-watch.Tests" />
    <InternalsVisibleTo Include="dotnet.Tests" />
    <InternalsVisibleTo Include="Microsoft.NET.Build.Tests" Key="$(MicrosoftSharedPublicKey)" />
    <InternalsVisibleTo Include="Microsoft.TemplateEngine.Cli" />
    <InternalsVisibleTo Include="Microsoft.TemplateEngine.Cli.UnitTests" />
  </ItemGroup>

  <Import Project="..\Cli\Microsoft.DotNet.FileBasedPrograms\Microsoft.DotNet.FileBasedPrograms.projitems" Label="Shared" />

  <ItemGroup>
    <EmbeddedResource Update="$(RepoRoot)src\Cli\Microsoft.DotNet.FileBasedPrograms\FileBasedProgramsResources.resx"
                      Generator="Microsoft.DotNet.Cli.Resources"
                      ClassName="Microsoft.DotNet.FileBasedPrograms.FileBasedProgramsResources" />
  </ItemGroup>

  <Import Project="$(RepoRoot)src\Cli\Microsoft.DotNet.Cli.Resources.Generator\Microsoft.DotNet.Cli.Resources.Generator.targets" />
</Project>
