pr: none

trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
    exclude:
    - release/*.0.2xx
    - release/*.0.3xx
    - release/*.0.4xx

resources:
  repositories:
  - repository: vmr
    type: github
    name: dotnet/dotnet
    endpoint: dotnet
    ref: $(Build.SourceBranch)

  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

parameters:
- name: vmrBranch
  displayName: dotnet/dotnet branch to push to
  type: string
  default: ' '

variables:
- template: /eng/common/templates-official/variables/pool-providers.yml@self

- ${{ if ne(parameters.vmrBranch, ' ') }}:
  - name: VmrBranch
    value: ${{ replace(parameters.vmrBranch, ' ', '') }}
- ${{ else }}:
  - name: VmrBranch
    value: ${{ replace(replace(variables['Build.SourceBranch'], 'refs/heads/', ''), 'refs/pull/', '') }}

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: $(DncEngInternalBuildPool)
        image: 1es-windows-2022
        os: windows

      sourceRepositoriesToScan:
        exclude:
        - repository: vmr

      componentgovernance:
        sourceScanPath: $(Agent.BuildDirectory)/vmr
        ignoreDirectories: $(Agent.BuildDirectory)/vmr/src

    stages:
    - stage: VMRSynchronization
      displayName: VMR Synchronization
      jobs:
      - template: /eng/pipelines/templates/jobs/vmr-synchronization.yml@self
        parameters:
          vmrBranch: ${{ variables.VmrBranch }}
