<Project Sdk="Microsoft.Build.Traversal" DefaultTargets="Pack">

  <ItemGroup>
    <ProjectReference Include="**\*.Manifest.proj" />
  </ItemGroup>

  <Target Name="GetBuiltinManifestLayoutInputs" Returns="@(_BuiltinManifestLayoutInput)">

    <PropertyGroup>
      <_VersionOverride Condition="'$(DotNet1xxWorkloadManifestVersion)' != ''">Version=$(DotNet1xxWorkloadManifestVersion)</_VersionOverride>
    </PropertyGroup>

    <MSBuild Projects="@(ProjectReference)"
             Targets="GetManifestLayoutInputs"
             Properties="ManifestDirectory=$(ManifestDirectory);$(_VersionOverride)">
      <Output TaskParameter="TargetOutputs" ItemName="_BuiltinManifestLayoutInput" />
    </MSBuild>
  </Target>

  <Target Name="LayoutBuiltinManifests" DependsOnTargets="GetBuiltinManifestLayoutInputs">
    <Copy SourceFiles="@(_BuiltinManifestLayoutInput)"
          DestinationFiles="@(_BuiltinManifestLayoutInput->'%(DestinationPath)')"
          SkipUnchangedFiles="true" />
  </Target>

</Project>