name: dotnet-sdk
version: 3.1.408
summary: Cross-Platform .NET Core SDK
description: |
  .NET Core SDK. https://dot.net/core.

grade: stable
confinement: classic

apps:
  dotnet:
    command: dotnet

base: core18

parts:
  dotnet-sdk:
      plugin: dump
      source: https://download.visualstudio.microsoft.com/download/pr/2054b462-43da-4c61-9e2d-d02167c71c40/a8be03062d9d770c8025c7de47ca366d/dotnet-sdk-3.1.408-linux-x64.tar.gz
      source-checksum: sha512/5e2c378addf337c1b7e44583718672e0791235150630f0b613353c8597342dcaae3b7c412b17d5e6d93d87b5708a6ca2dc16ff6e6c5a2101b224d24e6a5c4e7a
      stage-packages:
        - libicu60
        - libssl1.0.0
        - libcurl3
        - libgssapi-krb5-2
        - libstdc++6
        - zlib1g
        - libgcc1
        - libtinfo5
        - liblttng-ust0
        - liburcu6

  runtime-wrapper:
      plugin: dump
      source: .

