parameters:
  jobParameterSets: []
  oneESCompat:
    templateFolderName: templates
  locBranch: ''

jobs:
- ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/${{ parameters.locBranch }}')) }}:
  - template: /eng/common/${{ parameters.oneESCompat.templateFolderName }}/job/onelocbuild.yml
    parameters:
      CreatePr: true
      LclSource: lclFilesfromPackage
      LclPackageId: LCL-JUNO-PROD-DOTNETSDK
      MirrorBranch: ${{ parameters.locBranch }}
      MirrorRepo: sdk
- ${{ each jobParameters in parameters.jobParameterSets }}:
  - template: /eng/pipelines/templates/jobs/sdk-build.yml
    parameters:
      ${{ insert }}: ${{ parameters }}
      ${{ insert }}: ${{ jobParameters }}