//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.TemplateEngine.Authoring.CLI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizableStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizableStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.TemplateEngine.Authoring.CLI.LocalizableStrings", typeof(LocalizableStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given a template.config file, creates a &quot;localize&quot; directory next to it and exports the localization files into the created directory. If the localization files already exist, the existing translations will be preserved..
        /// </summary>
        internal static string command_export_help_description {
            get {
                return ResourceManager.GetString("command_export_help_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this option is specified, modified files will not be saved to file system and the changes will only be printed to console output..
        /// </summary>
        internal static string command_export_help_dryrun_description {
            get {
                return ResourceManager.GetString("command_export_help_dryrun_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of languages to be supported by this template. The following language list will be used as default if this option is omitted: cs, de, en, es, fr, it, ja, ko, pl, pt-BR, ru, tr, zh-Hans, zh-Hant.
        /// </summary>
        internal static string command_export_help_language_description {
            get {
                return ResourceManager.GetString("command_export_help_language_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When specified, subdirectories are also searched for template.json files..
        /// </summary>
        internal static string command_export_help_recursive_description {
            get {
                return ResourceManager.GetString("command_export_help_recursive_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the path to the template.json file. If a directory is given, template.json file will be searched within the directory. If --recursive options is specified, all the template.json files under the given directory and its subdirectories will be taken as input..
        /// </summary>
        internal static string command_export_help_templatePath_description {
            get {
                return ResourceManager.GetString("command_export_help_templatePath_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;export&quot; command for the following file was cancelled: &quot;{0}&quot;..
        /// </summary>
        internal static string command_export_log_cancelled {
            get {
                return ResourceManager.GetString("command_export_log_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution of &quot;export&quot; command has completed. {0} files were processed..
        /// </summary>
        internal static string command_export_log_executionEnded {
            get {
                return ResourceManager.GetString("command_export_log_executionEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating localization files for a template.json has failed.
        ///Reason: {0}.
        ///File Path: {1}..
        /// </summary>
        internal static string command_export_log_templateExportFailedWithError {
            get {
                return ResourceManager.GetString("command_export_log_templateExportFailedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating localization files for the following template.json file has failed: &quot;{0}&quot;..
        /// </summary>
        internal static string command_export_log_templateExportFailedWithException {
            get {
                return ResourceManager.GetString("command_export_log_templateExportFailedWithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization files were successfully generated for the template.json file at path &quot;{0}&quot;..
        /// </summary>
        internal static string command_export_log_templateExportSucceeded {
            get {
                return ResourceManager.GetString("command_export_log_templateExportSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find &quot;template.json&quot; file under the path &quot;{0}&quot;..
        /// </summary>
        internal static string command_export_log_templateJsonNotFound {
            get {
                return ResourceManager.GetString("command_export_log_templateJsonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validates the templates at given location..
        /// </summary>
        internal static string command_validate_help_description {
            get {
                return ResourceManager.GetString("command_validate_help_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location of template(s) to validate..
        /// </summary>
        internal static string command_validate_help_locationArg_description {
            get {
                return ResourceManager.GetString("command_validate_help_locationArg_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no entries&gt;.
        /// </summary>
        internal static string command_validate_info_no_entries {
            get {
                return ResourceManager.GetString("command_validate_info_no entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location &apos;{0}&apos;: found {1} templates..
        /// </summary>
        internal static string command_validate_info_scanning_completed {
            get {
                return ResourceManager.GetString("command_validate_info_scanning_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning location &apos;{0}&apos; for the templates...
        /// </summary>
        internal static string command_validate_info_scanning_in_progress {
            get {
                return ResourceManager.GetString("command_validate_info_scanning_in_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template {0}: the template is not valid..
        /// </summary>
        internal static string command_validate_info_summary_invalid {
            get {
                return ResourceManager.GetString("command_validate_info_summary_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; localization for the template {1}: the localization file is not valid. The localization will be skipped..
        /// </summary>
        internal static string command_validate_info_summary_loc_invalid {
            get {
                return ResourceManager.GetString("command_validate_info_summary_loc_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; localization for the template {1}: the localization file is valid..
        /// </summary>
        internal static string command_validate_info_summary_loc_valid {
            get {
                return ResourceManager.GetString("command_validate_info_summary_loc_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template {0}: the template is valid..
        /// </summary>
        internal static string command_validate_info_summary_valid {
            get {
                return ResourceManager.GetString("command_validate_info_summary_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found template {0}:.
        /// </summary>
        internal static string command_validate_info_template_header {
            get {
                return ResourceManager.GetString("command_validate_info_template_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found localization &apos;{0}&apos; for template {1}:.
        /// </summary>
        internal static string command_validate_info_template_loc_header {
            get {
                return ResourceManager.GetString("command_validate_info_template_loc_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Failed..
        /// </summary>
        internal static string command_verify_error_failed {
            get {
                return ResourceManager.GetString("command_verify_error_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument(s) {0} are not recognized. Must be one of: {1}..
        /// </summary>
        internal static string command_verify_error_unrecognizedArguments {
            get {
                return ResourceManager.GetString("command_verify_error_unrecognizedArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies pattern(s) defining files to be excluded from verification..
        /// </summary>
        internal static string command_verify_help_customExcludes_description {
            get {
                return ResourceManager.GetString("command_verify_help_customExcludes_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies pattern(s) defining files to be included to verification (all files are included if not specified)..
        /// </summary>
        internal static string command_verify_help_customIncludes_description {
            get {
                return ResourceManager.GetString("command_verify_help_customIncludes_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs the template with specified arguments and compares the result with expectations files..
        /// </summary>
        internal static string command_verify_help_description {
            get {
                return ResourceManager.GetString("command_verify_help_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set to true - all template output files will be verified, unless --exclude-pattern option is used..
        /// </summary>
        internal static string command_verify_help_disableDefaultExcludes_description {
            get {
                return ResourceManager.GetString("command_verify_help_disableDefaultExcludes_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set to true - the diff tool won&apos;t be automatically started by the Verifier on verification failures..
        /// </summary>
        internal static string command_verify_help_disableDiffTool_description {
            get {
                return ResourceManager.GetString("command_verify_help_disableDiffTool_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set to true - &apos;dotnet new&apos; command is expected to return non-zero return code..
        /// </summary>
        internal static string command_verify_help_expectFailure_description {
            get {
                return ResourceManager.GetString("command_verify_help_expectFailure_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the path to target directory to output the generated template to..
        /// </summary>
        internal static string command_verify_help_outputPath_description {
            get {
                return ResourceManager.GetString("command_verify_help_outputPath_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies optional scenario name to be used in the snapshot folder name..
        /// </summary>
        internal static string command_verify_help_scenarioName_description {
            get {
                return ResourceManager.GetString("command_verify_help_scenarioName_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies path to the directory with snapshot files..
        /// </summary>
        internal static string command_verify_help_snapshotsDirPath_description {
            get {
                return ResourceManager.GetString("command_verify_help_snapshotsDirPath_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the template to be verified. Can be already installed template or a template within local path specified with -p/--template-path option..
        /// </summary>
        internal static string command_verify_help_templateName_description {
            get {
                return ResourceManager.GetString("command_verify_help_templateName_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the path to the directory with template to be verified..
        /// </summary>
        internal static string command_verify_help_templatePath_description {
            get {
                return ResourceManager.GetString("command_verify_help_templatePath_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the Verifier expectations directory naming convention, by indicating which scenarios should be differentiated..
        /// </summary>
        internal static string command_verify_help_uniqueFor_description {
            get {
                return ResourceManager.GetString("command_verify_help_uniqueFor_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set to true - &apos;dotnet new&apos; command standard output and error contents will be verified along with the produced template files..
        /// </summary>
        internal static string command_verify_help_verifyOutputs_description {
            get {
                return ResourceManager.GetString("command_verify_help_verifyOutputs_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; command has encountered an error. See the logs for more details..
        /// </summary>
        internal static string generic_log_commandExecutionFailed {
            get {
                return ResourceManager.GetString("generic_log_commandExecutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while running the &quot;--{0}&quot; command. Error message: &quot;{1}&quot;. See the logs for more details..
        /// </summary>
        internal static string generic_log_commandExecutionFailedWithErrorMessage {
            get {
                return ResourceManager.GetString("generic_log_commandExecutionFailedWithErrorMessage", resourceCulture);
            }
        }
    }
}
