// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Runtime.CompilerServices;
using Microsoft.NET.TestFramework;

// Initialize TestContext before any tests run.
// In xUnit v3, the entry point is generated by the runner source generator,
// so we use a module initializer to set up the test context from command line args.
static class TestContextInitializer
{
    [ModuleInitializer]
    public static void Initialize()
    {
        TestCommandLine.HandleCommandLine(Environment.GetCommandLineArgs().Skip(1).ToArray());
    }
}
