<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(CurrentTargetFramework)</TargetFramework>
    <AssemblyName>dotnetup</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Installer\dotnetup.Library\dotnetup.Library.csproj" />
  </ItemGroup>
</Project>
