// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

using System.Threading.Tasks;
using Xunit;
using VerifyCS = Test.Utilities.CSharpCodeFixVerifier<
    Microsoft.CodeQuality.CSharp.Analyzers.ApiDesignGuidelines.CSharpImplementStandardExceptionConstructorsAnalyzer,
    Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.ImplementStandardExceptionConstructorsFixer>;
using VerifyVB = Test.Utilities.VisualBasicCodeFixVerifier<
    Microsoft.CodeQuality.VisualBasic.Analyzers.ApiDesignGuidelines.BasicImplementStandardExceptionConstructorsAnalyzer,
    Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.ImplementStandardExceptionConstructorsFixer>;

namespace Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.UnitTests
{
    public class ImplementStandardExceptionConstructorsFixerTests
    {
        #region CSharpUnitTests
        //Note: In the test cases you won't see a missing all 3 constructors scenario, because that will never occur since default constructor is always generated by system in that case

        [Fact(Skip = "https://github.com/dotnet/roslyn-analyzers/issues/2292")]
        public async Task TestCSFixMissingTwoCtors_Case1()
        {
            var code = @"
using System;
public class [|[|Foo|]|] : Exception
{
    public Foo()
    {
    }
}
";
            var fix = @"
using System;
public class Foo : Exception
{
    public Foo()
    {
    }

    public Foo(string message) : base(message)
    {
    }

    public Foo(string message, Exception innerException) : base(message, innerException)
    {
    }
}
";
            await new VerifyCS.Test
            {
                TestState = { Sources = { code } },
                FixedState = { Sources = { fix } },
                NumberOfFixAllIterations = 2,
            }.RunAsync();
        }

        [Fact(Skip = "https://github.com/dotnet/roslyn-analyzers/issues/2292")]
        public async Task TestCSFixMissingTwoCtors_Case2()
        {
            var code = @"
using System;
public class [|[|Foo|]|] : Exception
{
    public Foo(string message)
    {
    }
}
";
            var fix = @"
using System;
public class Foo : Exception
{
    public Foo(string message)
    {
    }

    public Foo()
    {
    }

    public Foo(string message, Exception innerException) : base(message, innerException)
    {
    }
}
";
            await new VerifyCS.Test
            {
                TestState = { Sources = { code } },
                FixedState = { Sources = { fix } },
                NumberOfFixAllIterations = 2,
            }.RunAsync();
        }

        [Fact(Skip = "https://github.com/dotnet/roslyn-analyzers/issues/2292")]
        public async Task TestCSFixMissingTwoCtors_Case3()
        {
            var code = @"
using System;
public class [|[|Foo|]|] : Exception
{
    public Foo(string message, Exception innerException)
    {
    }
}
";
            var fix = @"
using System;
public class Foo : Exception
{
    public Foo(string message, Exception innerException)
    {
    }

    public Foo()
    {
    }

    public Foo(string message) : base(message)
    {
    }
}
";
            await new VerifyCS.Test
            {
                TestState = { Sources = { code } },
                FixedState = { Sources = { fix } },
                NumberOfFixAllIterations = 2,
            }.RunAsync();
        }

        [Fact]
        public async Task TestCSFixMissingOneCtor_Case1()
        {
            var code = @"
using System;
public class [|Foo|] : Exception
{
    public Foo(string message): base(message)
    {
    }

    public Foo(string message, Exception innerException) : base(message, innerException)
    {
    }

}
";
            var fix = @"
using System;
public class Foo : Exception
{
    public Foo(string message): base(message)
    {
    }

    public Foo(string message, Exception innerException) : base(message, innerException)
    {
    }

    public Foo()
    {
    }
}
";
            await VerifyCS.VerifyCodeFixAsync(code, fix);
        }

        [Fact]
        public async Task TestCSFixMissingOneCtor_Case2()
        {
            var code = @"
using System;
public class [|Foo|] : Exception
{
    public Foo()
    {
    }

    public Foo(string message)
    {
    }

}
";
            var fix = @"
using System;
public class Foo : Exception
{
    public Foo()
    {
    }

    public Foo(string message)
    {
    }

    public Foo(string message, Exception innerException) : base(message, innerException)
    {
    }
}
";
            await VerifyCS.VerifyCodeFixAsync(code, fix);
        }

        [Fact]
        public async Task TestCSFixMissingOneCtor_Case3()
        {
            var code = @"
using System;
public class [|Foo|] : Exception
{
    public Foo()
    {
    }

    public Foo(string message, Exception innerException)
    {
    }

}
";
            var fix = @"
using System;
public class Foo : Exception
{
    public Foo()
    {
    }

    public Foo(string message, Exception innerException)
    {
    }

    public Foo(string message) : base(message)
    {
    }
}
";
            await VerifyCS.VerifyCodeFixAsync(code, fix);
        }

        #endregion

        #region BasicUnitTests
        //Note: In the test cases you won't see a missing all 3 constructors scenario, because that will never occur since default constructor is always generated by system in that case

        [Fact(Skip = "https://github.com/dotnet/roslyn-analyzers/issues/2292")]
        public async Task TestVBFixMissingTwoCtors_Case1()
        {
            var code = @"
Imports System
Public Class [|[|Foo|]|] : Inherits Exception
    Public Sub New()
    End Sub
End Class
";
            var fix = @"
Imports System
Public Class Foo : Inherits Exception
    Public Sub New()
    End Sub

    Public Sub New(message As String)
        MyBase.New(message)
    End Sub

    Public Sub New(message As String, innerException As Exception)
        MyBase.New(message, innerException)
    End Sub
End Class
";
            await new VerifyVB.Test
            {
                TestState = { Sources = { code } },
                FixedState = { Sources = { fix } },
                NumberOfFixAllIterations = 2,
            }.RunAsync();
        }

        [Fact(Skip = "https://github.com/dotnet/roslyn-analyzers/issues/2292")]
        public async Task TestVBFixMissingTwoCtors_Case2()
        {
            var code = @"
Imports System
Public Class [|[|Foo|]|] : Inherits Exception
    Public Sub New(message As String)
    End Sub
End Class
";
            var fix = @"
Imports System
Public Class Foo : Inherits Exception
    Public Sub New(message As String)
    End Sub

    Public Sub New()
    End Sub

    Public Sub New(message As String, innerException As Exception)
        MyBase.New(message, innerException)
    End Sub
End Class
";
            await new VerifyVB.Test
            {
                TestState = { Sources = { code } },
                FixedState = { Sources = { fix } },
                NumberOfFixAllIterations = 2,
            }.RunAsync();
        }

        [Fact(Skip = "https://github.com/dotnet/roslyn-analyzers/issues/2292")]
        public async Task TestVBFixMissingTwoCtors_Case3()
        {
            var code = @"
Imports System
Public Class [|[|Foo|]|] : Inherits Exception
    Public Sub New(message As String, innerException As Exception)
    End Sub
End Class
";
            var fix = @"
Imports System
Public Class Foo : Inherits Exception
    Public Sub New(message As String, innerException As Exception)
    End Sub

    Public Sub New()
    End Sub

    Public Sub New(message As String)
        MyBase.New(message)
    End Sub
End Class
";
            await new VerifyVB.Test
            {
                TestState = { Sources = { code } },
                FixedState = { Sources = { fix } },
                NumberOfFixAllIterations = 2,
            }.RunAsync();
        }

        [Fact]
        public async Task TestVBFixMissingOneCtor_Case1()
        {
            var code = @"
Imports System
Public Class [|Foo|] : Inherits Exception
    Public Sub New()
    End Sub

    Public Sub New(message As String)
    End Sub
End Class
";
            var fix = @"
Imports System
Public Class Foo : Inherits Exception
    Public Sub New()
    End Sub

    Public Sub New(message As String)
    End Sub

    Public Sub New(message As String, innerException As Exception)
        MyBase.New(message, innerException)
    End Sub
End Class
";
            await VerifyVB.VerifyCodeFixAsync(code, fix);
        }

        [Fact]
        public async Task TestVBFixMissingOneCtor_Case2()
        {
            var code = @"
Imports System
Public Class [|Foo|] : Inherits Exception
    Public Sub New()
    End Sub

    Public Sub New(message As String, innerException As Exception)
    End Sub
End Class
";
            var fix = @"
Imports System
Public Class Foo : Inherits Exception
    Public Sub New()
    End Sub

    Public Sub New(message As String, innerException As Exception)
    End Sub

    Public Sub New(message As String)
        MyBase.New(message)
    End Sub
End Class
";
            await VerifyVB.VerifyCodeFixAsync(code, fix);
        }

        [Fact]
        public async Task TestVBFixMissingOneCtor_Case3()
        {
            var code = @"
Imports System
Public Class [|Foo|] : Inherits Exception
    Public Sub New(message As String)
    End Sub

    Public Sub New(message As String, innerException As Exception)
    End Sub
End Class
";
            var fix = @"
Imports System
Public Class Foo : Inherits Exception
    Public Sub New(message As String)
    End Sub

    Public Sub New(message As String, innerException As Exception)
    End Sub

    Public Sub New()
    End Sub
End Class
";
            await VerifyVB.VerifyCodeFixAsync(code, fix);
        }
        #endregion
    }
}