name: dotnet-sdk
version: 6.0.410
summary: Cross-Platform .NET Core SDK
description: |
  .NET Core SDK. https://dot.net/core.

architectures:
  - build-on: amd64
    run-on: amd64

grade: stable
confinement: classic
base: core20

parts:
  dotnet-sdk:
      plugin: dump
      source: https://download.visualstudio.microsoft.com/download/pr/ac5809b0-7930-4ae9-9005-58f2fd7912f3/4cf0cb18d22a162b33149b1f28a8e045/dotnet-sdk-6.0.410-linux-x64.tar.gz
      source-checksum: sha512/8c85f5b10eb786c8cf31bf268131a2345a295d88d318310dc8457d831f0a587ec1600e43beb7f55aec2248483b9a95e905a468b592f0c910443b4aaa9baeb2e3
      stage-packages:      
      - libicu66
      - libgcc1
      - libstdc++6
      - libssl1.1
      - libcurl4
      - libgssapi-krb5-2
      - zlib1g
      - lldb
      - libunwind8
      - libtinfo5
      - liblttng-ust0
      - liburcu6

  runtime-wrapper:
      plugin: dump
      source: .

apps:
  dotnet:
    command: dotnet

