name: dotnet-sdk
version: 2.1.815
summary: Cross-Platform .NET Core SDK
description: |
  .NET Core SDK. https://dot.net/core.

grade: stable
confinement: classic

apps:
  dotnet:
    command: dotnet

base: core18

parts:
  dotnet-sdk:
      plugin: dump
      source: https://download.visualstudio.microsoft.com/download/pr/7fba29f6-aac9-4b53-a5f9-9b421bec6288/70ac39be0282331d18b535f64ea5f40a/dotnet-sdk-2.1.815-linux-x64.tar.gz
      source-checksum: sha512/e998ccb8b4e47a727141e85823637f2030df556d3056aadbdfbce4eca823fe4759ca0e0b2edaa6f83dd5b4cbb8a3b0046ff2c9eae96832e71dc6c13855998148
      stage-packages:
        - libicu60
        - libssl1.0.0
        - libcurl3
        - libgssapi-krb5-2
        - libstdc++6
        - zlib1g
        - libgcc1
        - libtinfo5
        - liblttng-ust0
        - liburcu6
        - lldb

  runtime-wrapper:
      plugin: dump
      source: .

