// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

#nullable enable

using Microsoft.AspNetCore.Http;

namespace Microsoft.AspNetCore.Watch.BrowserRefresh;

internal static class ApplicationPaths
{
    /// <summary>
    /// The PathString all listening URLs must be registered in
    /// </summary>
    /// <value><c>/_framework/</c></value>
    public static PathString FrameworkRoot { get; } = "/_framework";

    public static PathString BrowserTools { get; } = FrameworkRoot + "/dotnet-browser-tools";

    /// <summary>
    /// The provider only exposes the WebSocket endpoint and the cache clearing endpoint. Everything
    /// executable lives in the application's own build output.
    /// </summary>
    public static PathString BrowserToolsConnect { get; } = BrowserTools + "/connect";

    public static PathString BrowserToolsClearCache { get; } = BrowserTools + "/clear-cache";

    /// <summary>
    /// Legacy replay endpoint probed by the .NET 9 WebAssembly runtime.
    /// <see href="https://github.com/dotnet/aspnetcore/blob/release/9.0/src/Components/WebAssembly/WebAssembly/src/HotReload/WebAssemblyHotReload.cs">
    /// WebAssemblyHotReload.ApplyPreviousDeltasAsync</see> issues an unauthenticated
    /// <c>GET /_framework/blazor-hotreload</c> as soon as its Hot Reload agent is created and reports an
    /// error when the response is not a successful JSON payload. dotnet-watch replays updates over the
    /// authenticated WebSocket instead, so the application answers this probe with an empty update set.
    /// </summary>
    public static PathString LegacyPreviousDeltas { get; } = FrameworkRoot + "/blazor-hotreload";

    /// <summary>
    /// The application hosted browser tools configuration module generated by the Web SDK. It is a
    /// static web asset of the application, not a provider resource.
    /// </summary>
    public static PathString BrowserToolsConfigJS { get; } = FrameworkRoot + "/Microsoft.NET.Sdk.Web.DotNetWatch.BrowserTools.Config.js";
}
