<Project Sdk="MSTest.Sdk">

  <PropertyGroup>
    <TargetFramework>$(SdkTargetFramework)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HelixTasks\HelixTasks.csproj" />
    <ProjectReference Include="..\Microsoft.NET.TestFramework.MSTest\Microsoft.NET.TestFramework.MSTest.csproj" />
  </ItemGroup>

</Project>
