# This workflow creates a "backport" pull request by cherry-picking changes
# from the source pull request to the target branch when /backport to <branch>
# is commented on a pull request.
# Action: https://github.com/dotnet/sdk/actions/workflows/backport.yml
# Keep documentation/project-docs/developer-guide.md up to date with changes in
# this workflow.
name: Backport PR to branch
on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: write

env:
  DOTNET_CLI_TELEMETRY_SESSIONID: gha-${{ github.repository_id }}-${{ github.run_id }}-${{ github.run_attempt }}

jobs:
  backport:
    uses: dotnet/arcade/.github/workflows/backport-base.yml@945f3799137bb2145490baaadeeb8805f6d4be2d # main
    with:
        pr_labels: backport
        pr_description_template: |
          Backport of #%source_pr_number% to %target_branch%

          /cc %cc_users%
