name: Backport PR to branch
on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: write

jobs:
  backport:
    uses: dotnet/arcade/.github/workflows/backport-base.yml@main
    with:
        pr_description_template: |
          Backport of #%source_pr_number% to %target_branch%

          /cc %cc_users%

          > [!Important]
          > Make sure to create a merge commit. *Do not squash*. If you squash, the next inter-branch PR will list all of the same commits. See [SDK-PR-guide.md](https://github.com/dotnet/sdk/blob/main/documentation/project-docs/SDK-PR-guide.md#reviewing-and-merging-inter-branch-codeflow) for more information.