name: Check if target branch is in lockdown
on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
permissions:
  contents: read
  pull-requests: read
jobs:
  check:
    if: contains(github.event.pull_request.labels.*.name, 'Branch Lockdown')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Retun error if branch is in lockdown
        run: echo "Branch is in lockdown. Please contact the branch owner to get it unlocked." && exit 1