name: Check if target branch is in lockdown
on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
permissions:
  contents: read
  pull-requests: read
jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install jq
      run: sudo apt-get install jq
    - name: Check if pr has branch-lockdown label
      run: |
        if [[ $(jq -r '.pull_request.labels[].name' $GITHUB_EVENT_PATH) == "Branch Lockdown" ]]; then
          echo "Branch is in lockdown"
          exit 1
        else
          echo "Branch is not in lockdown"
        fi