name: Copilot Setup Steps

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

permissions:
  contents: read

jobs:

  copilot-setup-steps:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_SESSIONID: gha-${{ github.repository_id }}-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Do an initial build to ensure all dependencies are restored
        continue-on-error: true
        run: |
          ./build.sh
      - name: Put repo-local dotnet install on PATH
        run: |
          echo "PATH=$PWD/.dotnet:$PATH" >> $GITHUB_ENV

      - name: Check dotnet version
        run: |
          dotnet --version

      # For MCP servers like nuget's
      - name: Install .NET 10.x
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: |
            10.x
          dotnet-quality: preview

      # for MCP servers
      - name: Install .NET 8.x
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: |
            8.x
