name: Inter-branch merge workflow
on:
  push:
    branches:
      - main
      - release/**

permissions:
  contents: write
  pull-requests: write

env:
  DOTNET_CLI_TELEMETRY_SESSIONID: gha-${{ github.repository_id }}-${{ github.run_id }}-${{ github.run_attempt }}

jobs:
  Merge:
    uses: dotnet/arcade/.github/workflows/inter-branch-merge-base.yml@306225d7029934938d109e18df390f04e366a68d # main