name: Inter-branch merge workflow
on:
  push:
    branches:
      - main
      - release/**

permissions:
  contents: write
  pull-requests: write

env:
  DOTNET_CLI_TELEMETRY_SESSIONID: gha-${{ github.repository_id }}-${{ github.run_id }}-${{ github.run_attempt }}

jobs:
  Merge:
    uses: dotnet/arcade/.github/workflows/inter-branch-merge-base.yml@8556dfa0f523487f65aa1cb737f36b52281accbf # main