name: PR Main Branch Warning
on:
  pull_request_target:
    types: [opened]
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add warning comment to PR targeting main
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `This PR is targeting \`main\`, which is now for .NET 11-facing work. If you intended to target .NET 10, either retarget this PR to \`release/10.0.1xx\` or make sure you backport the change to \`release/10.0.1xx\` after merging. See https://github.com/dotnet/sdk/issues/50394 for more details.`
            })
