name: Remove Lockdown Label from PRs

on:
  pull_request:
    types: [closed]

permissions:
    actions: write
    pull-requests: write

jobs:
    remove-labels:
        if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'Branding')
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout repository
            uses: actions/checkout@v2

        # flagged user-visible change: replaced shell script with JS to check <VersionFeature>user-visible change: replaced shell script with JS to check <VersionFeature>
        -   name: PR's only change is <VersionFeature> in eng/Versions.propsly change is <VersionFeature> in eng/Versions.props
            uses: actions/github-script@v4
            with:
                script: |
                    const prNumber = context.payload.pull_request.number;
                    const { data: files } = await github.pulls.listFiles({
                        owner: context.repo.owner,
                        repo: context.repo.repo,    repo: context.repo.repo,
                        pull_number: prNumber
                    });
                    // If files other than eng/Versions.props are changed, output message and exit
                    if (files.any(file => file.filename !== "eng/Versions.props")) {
                        console.log("❌ Changes in eng/Versions.props other than <VersionFeature> found");
                        core.exportVariable("only_version_feature_changed", "false");
                        return;
                    }
                    // Iterate through the patch of eng/Versions.props to check for changes other than <VersionFeature>
                    const versionsPropsFile = files.find(file => file.filename === "eng/Versions.props");
                    const patchLines = versionsPropsFile.patch.split("\n").filter(l => l.startsWith("+") || l.startsWith("-"));
                    for (const line of patchLines) {
                        if (!line.includes("<VersionFeature>")) {
                            console.log("❌ Changes in eng/Versions.props other than <VersionFeature> found");
                            core.exportVariable("only_version_feature_changed", "false");
                            return;
                        }
                    }
                    console.log("✅ PR's only change is <VersionFeature> in eng/Versions.props");
                    core.exportVariable("only_version_feature_changed", "true");

        -   name: Remove Branch Lockdown label from other PRs targeting this branch
            if: steps.PR_has_Branding_label.outputs.has_branding_label == 'true' && steps.PR_only_change_is_VersionFeature_in_eng_Versions_props.outputs.only_version_feature_changed == 'true'
            uses: actions/github-script@v4
            with:
                script: |
                    const prs = await github.pulls.list({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        state: 'open',
                        base: github.event.pull_request.base.ref,
                        per_page: 300
                    });
                    const filtered_prs = prs.data
                        .filter(pr => pr.number !== github.context.payload.pull_request.number)
                        .filter(pr => pr.labels.map(label => label.name).includes('Branch Lockdown'));
                    for (const pr of filtered_prs) {
                        await github.issues.removeLabel({
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            issue_number: pr.number,
                            name: 'Branch Lockdown'
                        });
                        console.log(`Removed Branch Lockdown label from PR #${pr.number}`);
                    }